import type { Build } from '@/src/types/data';
import type { CharacterKey } from '@/src/types/good';

// https://tinyurl.com/genshinbuilds
// 1/26/24
export const builds: Record<CharacterKey, Build> = {
	Traveler: {
		key: 'Traveler',
		role: 'DPS',
		weapon: ['SwordOfNarzissenkreuz'],
		group: 0,
		artifact: ['GladiatorsFinale'],
		mainStat: { sands: 'atk_', goblet: 'atk_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'eleMas', 'atk'],
	},
	// Pyro
	Amber: {
		key: 'Amber',
		role: 'Support',
		weapon: ['ElegyForTheEnd', 'FavoniusWarbow', 'SacrificialBow', 'TheViridescentHunt'],
		group: 0,
		artifact: ['NoblesseOblige', 'Instructor', 'TheExile'],
		mainStat: { sands: ['enerRech_', 'atk_'], goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'atk_', 'eleMas', 'atk'],
	},
	Xiangling: {
		key: 'Xiangling',
		role: 'Off-Field DPS',
		weapon: [
			'StaffOfTheScarletSands',
			['StaffOfHoma', 'LumidouceElegy', 'EngulfingLightning', 'TheCatch'],
			[
				'PrimordialJadeWingedSpear',
				'SkywardSpine',
				'CalamityQueller',
				'Deathmatch',
				'BalladOfTheFjords',
			],
			['VortexVanquisher', 'WavebreakersFin', 'DragonsBane'],
			'MissiveWindspear',
			'KitainCrossSpear',
			'LithicSpear',
			'FavoniusLance',
			'PrototypeStarglitter',
		],
		group: 0,
		artifact: [
			'EmblemOfSeveredFate',
			'CrimsonWitchOfFlames',
			'NoblesseOblige',
			'DeepwoodMemories',
		],
		mainStat: {
			sands: ['enerRech_', 'atk_', 'eleMas'],
			goblet: 'pyro_dmg_',
			circlet: 'critRD_',
		},
		subStat: ['enerRech_', 'critRD_', 'atk_', 'eleMas', 'atk'],
	},
	Bennett: {
		key: 'Bennett',
		role: 'Support and Damage',
		weapon: [
			'MistsplitterReforged',
			'AquilaFavonia',
			'SkywardBlade',
			'FreedomSworn',
			'TheAlleyFlash',
			'FinaleOfTheDeep',
			'SapwoodBlade',
			'BlackcliffLongsword',
			'PrototypeRancour',
			'FesteringDesire',
		],
		group: 0,
		artifact: ['NoblesseOblige', 'EmblemOfSeveredFate', 'CrimsonWitchOfFlames'],
		mainStat: { sands: ['atk_', 'enerRech_'], goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'eleMas'],
	},
	Xinyan: {
		key: 'Xinyan',
		role: 'Physical DPS',
		weapon: [
			'RedhornStonethresher',
			'SkywardPride',
			'SerpentSpine',
			'TheUnforged',
			'SongOfBrokenPines',
			'WolfsGravestone',
			'LuxuriousSeaLord',
			'SnowTombedStarsilver',
			'PrototypeArchaic',
		],
		group: 0,
		artifact: ['PaleFlame'],
		mainStat: { sands: ['atk_', 'enerRech_'], goblet: 'physical_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'def_'],
	},
	Yanfei: {
		key: 'Yanfei',
		role: 'DPS',
		weapon: [
			['SkywardAtlas', 'MemoryOfDust'],
			'LostPrayerToTheSacredWinds',
			'KagurasVerity',
			'TheWidsith',
			'DodocoTales',
			'SolarPearl',
			'BlackcliffAgate',
			'MappaMare',
		],
		group: 0,
		artifact: [
			'CrimsonWitchOfFlames',
			'GildedDreams',
			'WanderersTroupe',
			'ShimenawasReminiscence',
			'RetracingBolide',
		],
		mainStat: { sands: ['atk_', 'eleMas'], goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'eleMas', 'atk'],
	},
	Thoma: {
		key: 'Thoma',
		role: 'Burgeon',
		weapon: [
			'KitainCrossSpear',
			'FavoniusLance',
			'DragonsBane',
			'Moonpiercer',
			'BlackTassel',
			'RightfulReward',
		],
		group: 1,
		artifact: ['FlowerOfParadiseLost', 'GildedDreams', 'CrimsonWitchOfFlames'],
		mainStat: { sands: ['enerRech_', 'eleMas'], goblet: 'eleMas', circlet: 'eleMas' },
		subStat: ['enerRech_', 'eleMas', 'hp_', 'hp', 'critRate_'],
	},
	Chevreuse: {
		key: 'Chevreuse',
		role: 'Support',
		weapon: [
			'FavoniusLance',
			'DialoguesOfTheDesertSages',
			['BlackTassel', 'RightfulReward'],
			'PrototypeStarglitter',
		],
		group: 1,
		artifact: ['NoblesseOblige', 'OceanHuedClam', 'SongOfDaysPast', 'MaidenBeloved'],
		mainStat: { sands: ['hp_', 'enerRech_'], goblet: 'hp_', circlet: ['hp_', 'heal_'] },
		subStat: ['enerRech_', 'hp_', 'critRate_', 'hp', 'eleMas'],
	},
	Gaming: {
		key: 'Gaming',
		role: 'Vaporize DPS',
		weapon: [
			['AThousandBlazingSuns', 'SerpentSpine'],
			['RedhornStonethresher', 'Verdict', 'BeaconOfTheReedSea'],
			['FruitfulHook', 'WolfsGravestone', 'Rainslasher'],
			'TheUnforged',
			['MailedFlower', 'LithicBlade'],
			['TidalShadow', 'UltimateOverlordsMegaMagicSword'],
		],
		group: 1,
		artifact: [
			['CrimsonWitchOfFlames', 'MarechausseeHunter'],
			'GildedDreams',
			'VermillionHereafter',
		],
		mainStat: {
			sands: ['eleMas', 'atk_', 'enerRech_'],
			goblet: 'pyro_dmg_',
			circlet: 'critRD_',
		},
		subStat: ['enerRech_', 'critRD_', 'eleMas', 'atk_', 'atk'],
	},
	Diluc: {
		key: 'Diluc',
		role: 'DPS',
		weapon: [
			['RedhornStonethresher', 'BeaconOfTheReedSea'],
			'SerpentSpine',
			['WolfsGravestone', 'TheUnforged'],
			['Rainslasher', 'MailedFlower'],
			'SkywardPride',
			'SongOfBrokenPines',
			['BlackcliffSlasher', 'LuxuriousSeaLord'],
			'PrototypeArchaic',
		],
		group: 0,
		artifact: ['CrimsonWitchOfFlames', 'GildedDreams', 'GladiatorsFinale'],
		mainStat: { sands: ['eleMas', 'atk_'], goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'eleMas', 'enerRech_'],
	},
	Klee: {
		key: 'Klee',
		role: 'DPS',
		weapon: [
			'TheWidsith',
			['LostPrayerToTheSacredWinds', 'KagurasVerity'],
			['SkywardAtlas', 'TulaytullahsRemembrance'],
			'MemoryOfDust',
			'SolarPearl',
			'DodocoTales',
			'BlackcliffAgate',
			'MappaMare',
			'MagicGuide',
		],
		group: 0,
		artifact: ['Lavawalker', 'CrimsonWitchOfFlames', 'WanderersTroupe', 'MarechausseeHunter'],
		mainStat: { sands: 'atk_', goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'eleMas', 'enerRech_', 'atk'],
	},
	HuTao: {
		key: 'HuTao',
		role: 'DPS',
		weapon: [
			'StaffOfHoma',
			'StaffOfTheScarletSands',
			['BalladOfTheFjords', 'LumidouceElegy'],
			['DragonsBane', 'Deathmatch'],
			'PrimordialJadeWingedSpear',
			'LithicSpear',
			'MissiveWindspear',
			['WhiteTassel', 'BlackcliffPole', 'KitainCrossSpear', 'RightfulReward'],
		],
		group: 0,
		artifact: [
			'CrimsonWitchOfFlames',
			'ShimenawasReminiscence',
			'GildedDreams',
			'RetracingBolide',
			'MarechausseeHunter',
		],
		mainStat: { sands: ['hp_', 'eleMas'], goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'eleMas', 'hp_', 'atk_', 'enerRech_'],
	},
	Yoimiya: {
		key: 'Yoimiya',
		role: 'DPS',
		weapon: [
			'ThunderingPulse',
			'AquaSimulacra',
			'PolarStar',
			['HuntersPath', 'SkywardHarp'],
			'Slingshot',
			'Rust',
		],
		group: 0,
		artifact: [
			'ShimenawasReminiscence',
			'CrimsonWitchOfFlames',
			'GildedDreams',
			'EchoesOfAnOffering',
			'RetracingBolide',
		],
		mainStat: { sands: ['atk_', 'eleMas'], goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'eleMas', 'enerRech_', 'atk'],
	},
	Dehya: {
		key: 'Dehya',
		role: 'Support',
		weapon: [
			'FavoniusGreatsword',
			['WolfsGravestone', 'MakhairaAquamarine'],
			'TheBell',
			'PrototypeArchaic',
		],
		group: 0,
		artifact: [
			'TenacityOfTheMillelith',
			'Instructor',
			'OceanHuedClam',
			'MaidenBeloved',
			'DeepwoodMemories',
		],
		mainStat: { sands: 'hp_', goblet: 'hp_', circlet: ['hp_', 'critRate_'] },
		subStat: ['hp_', 'hp', 'eleMas', 'atk_', 'atk'],
	},
	Lyney: {
		key: 'Lyney',
		role: 'DPS',
		weapon: [
			['TheFirstGreatMagic', 'AstralVulturesCrimsonPlumage'],
			'AquaSimulacra',
			'ThunderingPulse',
			'SkywardHarp',
			'AmosBow',
			['PolarStar', 'SongOfStillness', 'PrototypeCrescent'],
			['ScionOfTheBlazingSun', 'BlackcliffWarbow'],
		],
		group: 0,
		artifact: [
			'MarechausseeHunter',
			['Lavawalker', 'VermillionHereafter', 'ShimenawasReminiscence'],
			['RetracingBolide', 'DesertPavilionChronicle'],
			'WanderersTroupe',
		],
		mainStat: { sands: 'atk_', goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'atk'],
	},
	Arlecchino: {
		key: 'Arlecchino',
		role: 'DPS',
		weapon: [
			'CrimsonMoonsSemblance',
			['PrimordialJadeWingedSpear', 'StaffOfTheScarletSands'],
			['StaffOfHoma', 'LumidouceElegy', 'CalamityQueller'],
			'VortexVanquisher',
			'Deathmatch',
			'WhiteTassel',
			'BalladOfTheFjords',
		],
		group: 0,
		artifact: ['FragmentOfHarmonicWhimsy', 'GladiatorsFinale', 'DesertPavilionChronicle'],
		mainStat: { sands: ['atk_', 'eleMas'], goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'eleMas', 'atk_', 'atk'],
	},
	Mavuika: {
		key: 'Mavuika',
		role: 'DPS',
		weapon: [
			'AThousandBlazingSuns',
			['BeaconOfTheReedSea', 'Verdict'],
			['TheUnforged', 'FangOfTheMountainKing', 'RedhornStonethresher', 'WolfsGravestone'],
			'MailedFlower',
			'TidalShadow',
			'SerpentSpine',
			'TalkingStick',
		],
		group: 0,
		artifact: ['ObsidianCodex', 'MarechausseeHunter', 'ScrollOfTheHeroOfCinderCity'],
		mainStat: { sands: ['eleMas', 'atk_'], goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'eleMas', 'atk'],
	},
	// Dendro
	Collei: {
		key: 'Collei',
		role: 'Support',
		weapon: ['ElegyForTheEnd', 'PolarStar', 'SacrificialBow', 'FavoniusWarbow'],
		group: 0,
		artifact: [
			'DeepwoodMemories',
			'NoblesseOblige',
			'TenacityOfTheMillelith',
			'Instructor',
			'GildedDreams',
			'TheExile',
		],
		mainStat: {
			sands: ['enerRech_', 'atk_', 'eleMas'],
			goblet: ['dendro_dmg_', 'eleMas'],
			circlet: ['critRD_', 'eleMas'],
		},
		subStat: ['enerRech_', 'critRD_', ['atk_', 'eleMas']],
	},
	Yaoyao: {
		key: 'Yaoyao',
		role: 'Support',
		weapon: [
			'FavoniusLance',
			'DialoguesOfTheDesertSages',
			['BlackTassel', 'RightfulReward'],
			'Moonpiercer',
			'KitainCrossSpear',
		],
		group: 1,
		artifact: [
			'DeepwoodMemories',
			'TenacityOfTheMillelith',
			'Instructor',
			'OceanHuedClam',
			'MaidenBeloved',
			'FlowerOfParadiseLost',
			'GildedDreams',
		],
		mainStat: { sands: ['hp_', 'enerRech_'], goblet: 'hp_', circlet: 'heal_' },
		subStat: ['enerRech_', 'hp_', 'critRate_', 'hp'],
	},
	Kaveh: {
		key: 'Kaveh',
		role: 'Bloom/Burgeon Driver',
		weapon: [
			'FavoniusGreatsword',
			'SacrificialGreatsword',
			'MailedFlower',
			['WolfsGravestone', 'SongOfBrokenPines'],
			['MakhairaAquamarine', 'KatsuragikiriNagamasa'],
			['SkywardPride', 'ForestRegalia', 'Rainslasher'],
		],
		group: 0,
		artifact: [
			'DeepwoodMemories',
			'OceanHuedClam',
			'FlowerOfParadiseLost',
			'Instructor',
			'GildedDreams',
		],
		mainStat: {
			sands: ['enerRech_', 'eleMas'],
			goblet: 'eleMas',
			circlet: ['eleMas', 'critRate_'],
		},
		subStat: ['enerRech_', 'eleMas', 'critRate_'],
	},
	Kirara: {
		key: 'Kirara',
		role: 'Shield Support',
		weapon: [
			'KeyOfKhajNisut',
			'SapwoodBlade',
			'TheDockhandsAssistant',
			'FavoniusSword',
			'FreedomSworn',
			'SacrificialSword',
		],
		group: 0,
		artifact: ['Instructor', 'DeepwoodMemories', ['NoblesseOblige', 'TenacityOfTheMillelith']],
		mainStat: { sands: ['hp_', 'enerRech_'], goblet: 'hp_', circlet: ['hp_', 'critRate_'] },
		subStat: ['enerRech_', 'hp_', 'critRate_', 'hp'],
	},
	Tighnari: {
		key: 'Tighnari',
		role: 'Quick Swap DPS',
		weapon: [
			'HuntersPath',
			['AstralVulturesCrimsonPlumage', 'AquaSimulacra', 'PolarStar', 'TheFirstGreatMagic'],
			['SkywardHarp', 'ThunderingPulse'],
			['ElegyForTheEnd', 'AmosBow', 'FadingTwilight'],
			['ScionOfTheBlazingSun', 'TheViridescentHunt'],
			['Slingshot', 'RangeGauge', 'WindblumeOde', 'SongOfStillness'],
			'PrototypeCrescent',
		],
		group: 1,
		artifact: [['WanderersTroupe', 'GildedDreams'], 'EmblemOfSeveredFate', 'DeepwoodMemories'],
		mainStat: {
			sands: ['atk_', 'eleMas', 'enerRech_'],
			goblet: 'dendro_dmg_',
			circlet: 'critRD_',
		},
		subStat: ['critRD_', ['eleMas', 'atk_'], 'enerRech_'],
	},
	Nahida: {
		key: 'Nahida',
		role: 'DPS & Support',
		weapon: [
			'AThousandFloatingDreams',
			'KagurasVerity',
			'SacrificialFragments',
			'WanderingEvenstar',
			['TheWidsith', 'SacrificialJade'],
			['SkywardAtlas', 'LostPrayerToTheSacredWinds', 'MemoryOfDust', 'SolarPearl'],
			'FavoniusCodex',
			['MappaMare', 'MagicGuide', 'HakushinRing'],
			'ThrillingTalesOfDragonSlayers',
			'PrototypeAmber',
		],
		group: 0,
		artifact: [
			'DeepwoodMemories',
			['GildedDreams', 'GoldenTroupe'],
			'TenacityOfTheMillelith',
			'FlowerOfParadiseLost',
		],
		mainStat: {
			sands: 'eleMas',
			goblet: ['eleMas', 'dendro_dmg_'],
			circlet: ['eleMas', 'critRD_'],
		},
		subStat: ['enerRech_', ['critRD_', 'eleMas'], 'atk_'],
	},
	Alhaitham: {
		key: 'Alhaitham',
		role: 'Spread DPS',
		weapon: [
			'LightOfFoliarIncision',
			'PrimordialJadeCutter',
			['MistsplitterReforged', 'HaranGeppakuFutsu'],
			'FreedomSworn',
			'WolfFang',
			'ToukabouShigure',
			'TheBlackSword',
			['SummitShaper', 'IronSting', 'BlackcliffLongsword', 'HarbingerOfDawn'],
			['XiphosMoonlight', 'FesteringDesire'],
			'SkywardBlade',
		],
		group: 0,
		artifact: ['GildedDreams', 'DeepwoodMemories'],
		mainStat: { sands: ['eleMas', 'atk_'], goblet: 'dendro_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'eleMas', 'atk_', 'atk'],
	},
	Baizhu: {
		key: 'Baizhu',
		role: 'Support',
		weapon: [
			'JadefallsSplendor',
			'PrototypeAmber',
			'FavoniusCodex',
			'HakushinRing',
			'ThrillingTalesOfDragonSlayers',
			'AThousandFloatingDreams',
		],
		group: 1,
		artifact: ['DeepwoodMemories', 'OceanHuedClam', 'Instructor', 'NoblesseOblige'],
		mainStat: { sands: ['hp_', 'enerRech_'], goblet: 'hp_', circlet: ['hp_', 'heal_'] },
		subStat: ['enerRech_', 'hp_', 'hp'],
	},
	Emilie: {
		key: 'Emilie',
		role: 'Off-Field DPS',
		weapon: [
			'LumidouceElegy',
			'CalamityQueller',
			'StaffOfHoma',
			['EngulfingLightning', 'StaffOfTheScarletSands'],
			['PrimordialJadeWingedSpear', 'CrimsonMoonsSemblance'],
			'Deathmatch',
			'SkywardSpine',
			['MissiveWindspear', 'LithicSpear', 'ProspectorsDrill'],
			'FavoniusLance',
			'KitainCrossSpear',
		],
		group: 0,
		artifact: ['UnfinishedReverie', 'DeepwoodMemories', 'GoldenTroupe'],
		mainStat: { sands: 'atk_', goblet: 'dendro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'atk'],
	},
	Kinich: {
		key: 'Kinich',
		role: 'DPS',
		weapon: [
			'FangOfTheMountainKing',
			'BeaconOfTheReedSea',
			'SerpentSpine',
			'Verdict',
			['EarthShaker', 'WolfsGravestone', 'RedhornStonethresher'],
		],
		group: 0,
		artifact: [
			'ObsidianCodex',
			'UnfinishedReverie',
			'GoldenTroupe',
			'DeepwoodMemories',
			'MarechausseeHunter',
		],
		mainStat: { sands: 'atk_', goblet: 'dendro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_'],
	},
	// Hydro
	Xingqiu: {
		key: 'Xingqiu',
		role: 'Off-Field DPS',
		weapon: [
			'PrimordialJadeCutter',
			'MistsplitterReforged',
			'HaranGeppakuFutsu',
			['LightOfFoliarIncision', 'Absolution'],
			['SkywardBlade', 'WolfFang'],
			'SummitShaper',
			['FavoniusSword', 'FleuveCendreFerryman'],
			'FinaleOfTheDeep',
			['FesteringDesire', 'SacrificialSword', 'AmenomaKageuchi', 'HarbingerOfDawn'],
			['SapwoodBlade', 'FreedomSworn', 'LionsRoar'],
		],
		group: 0,
		artifact: ['EmblemOfSeveredFate', 'NoblesseOblige', 'NymphsDream', 'BlizzardStrayer'],
		mainStat: { sands: ['enerRech_', 'atk_'], goblet: 'hydro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'eleMas', 'atk'],
	},
	Barbara: {
		key: 'Barbara',
		role: 'Support',
		weapon: [
			'ThrillingTalesOfDragonSlayers',
			'EverlastingMoonglow',
			'PrototypeAmber',
			'FavoniusCodex',
		],
		group: 0,
		artifact: [['MaidenBeloved', 'OceanHuedClam'], 'Instructor'],
		mainStat: { sands: 'hp_', goblet: 'hp_', circlet: 'heal_' },
		subStat: ['hp_', 'hp'],
	},
	Candace: {
		key: 'Candace',
		role: 'Support',
		weapon: [
			'FavoniusLance',
			'EngulfingLightning',
			['StaffOfHoma', 'Deathmatch', 'TheCatch'],
			'PrototypeStarglitter',
			'SkywardSpine',
			'BlackTassel',
		],
		group: 1,
		artifact: ['EmblemOfSeveredFate'],
		mainStat: {
			sands: ['enerRech_', 'hp_'],
			goblet: ['hp_', 'hydro_dmg_'],
			circlet: ['hp_', 'critRD_'],
		},
		subStat: ['enerRech_', 'critRate_', 'hp_', 'hp'],
	},
	Tartaglia: {
		key: 'Tartaglia',
		role: 'DPS',
		weapon: [
			['PolarStar', 'AquaSimulacra', 'ThunderingPulse', 'HuntersPath'],
			'SkywardHarp',
			['AmosBow', 'PrototypeCrescent', 'TheViridescentHunt'],
			['KingsSquire', 'MouunsMoon'],
			[
				'Hamayumi',
				'FadingTwilight',
				'BlackcliffWarbow',
				'TheStringless',
				'ElegyForTheEnd',
				'Rust',
			],
		],
		group: 0,
		artifact: ['NymphsDream', 'HeartOfDepth', 'ShimenawasReminiscence'],
		mainStat: { sands: 'atk_', goblet: 'hydro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'eleMas', 'enerRech_', 'atk'],
	},
	Mona: {
		key: 'Mona',
		role: 'Burst Support',
		weapon: [
			'ThrillingTalesOfDragonSlayers',
			'FavoniusCodex',
			'AThousandFloatingDreams',
			'PrototypeAmber',
			'WineAndSong',
		],
		group: 0,
		artifact: ['NoblesseOblige', 'Instructor', 'TenacityOfTheMillelith'],
		mainStat: {
			sands: ['enerRech_', 'atk_'],
			goblet: ['hydro_dmg_', 'atk_'],
			circlet: 'critRate_',
		},
		subStat: ['enerRech_', 'critRate_', 'atk_'],
	},
	SangonomiyaKokomi: {
		key: 'SangonomiyaKokomi',
		role: 'Support',
		weapon: [
			'ThrillingTalesOfDragonSlayers',
			'PrototypeAmber',
			'HakushinRing',
			'SacrificialFragments',
		],
		group: 0,
		artifact: [['OceanHuedClam', 'TenacityOfTheMillelith'], 'MaidenBeloved'],
		mainStat: { sands: ['enerRech_', 'hp_'], goblet: 'hp_', circlet: ['heal_', 'hp_'] },
		subStat: ['enerRech_', 'hp_', 'atk_', 'hp', 'atk'],
	},
	KamisatoAyato: {
		key: 'KamisatoAyato',
		role: 'DPS',
		weapon: [
			['HaranGeppakuFutsu', 'PrimordialJadeCutter'],
			'MistsplitterReforged',
			'LightOfFoliarIncision',
			'TheBlackSword',
			['SkywardBlade', 'SplendorOfTranquilWaters'],
			'SummitShaper',
			['FinaleOfTheDeep', 'KagotsurubeIsshin'],
			'LionsRoar',
			['HarbingerOfDawn', 'TheFlute', 'SwordOfNarzissenkreuz'],
		],
		group: 0,
		artifact: [
			['HeartOfDepth', 'GladiatorsFinale', 'NymphsDream'],
			'BlizzardStrayer',
			'ThunderingFury',
			'EchoesOfAnOffering',
		],
		mainStat: { sands: 'atk_', goblet: 'hydro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'hp_', 'eleMas', 'atk'],
	},
	Yelan: {
		key: 'Yelan',
		role: 'Off-Field DPS',
		weapon: [
			'AquaSimulacra',
			'SilvershowerHeartstrings',
			['MouunsMoon', 'TheStringless', 'Slingshot'],
			['HuntersPath', 'PolarStar', 'ThunderingPulse', 'SkywardHarp'],
			'FadingTwilight',
			'RecurveBow',
		],
		group: 1,
		artifact: ['EmblemOfSeveredFate'],
		mainStat: {
			sands: ['enerRech_', 'hp_'],
			goblet: ['hydro_dmg_', 'hp_'],
			circlet: ['critRD_', 'hp_'],
		},
		subStat: ['enerRech_', ['hp_', 'critRD_'], 'hp'],
	},
	Nilou: {
		key: 'Nilou',
		role: 'Bloom Support',
		weapon: [
			'KeyOfKhajNisut',
			'TheDockhandsAssistant',
			['FreedomSworn', 'XiphosMoonlight'],
			['IronSting', 'ToukabouShigure'],
			['FavoniusSword', 'FesteringDesire', 'SacrificialSword', 'SapwoodBlade'],
			'PrimordialJadeCutter',
		],
		group: 0,
		artifact: ['VourukashasGlow', 'DeepwoodMemories'],
		mainStat: { sands: ['hp_', 'enerRech_'], goblet: 'hp_', circlet: 'hp_' },
		subStat: ['hp_', 'hp', 'enerRech_', 'eleMas', 'critRD_'],
	},
	Neuvillette: {
		key: 'Neuvillette',
		role: 'DPS',
		weapon: [
			'TomeOfTheEternalFlow',
			['SacrificialJade', 'SurfsUp'],
			[
				'JadefallsSplendor',
				'PrototypeAmber',
				'CashflowSupervision',
				'TheWidsith',
				'KagurasVerity',
				'LostPrayerToTheSacredWinds',
			],
		],
		group: 1,
		artifact: [
			'MarechausseeHunter',
			'HeartOfDepth',
			['RetracingBolide', 'WanderersTroupe', 'NymphsDream'],
		],
		mainStat: { sands: 'hp_', goblet: ['hydro_dmg_', 'hp_'], circlet: ['critRD_', 'hp_'] },
		subStat: ['enerRech_', ['critRD_', 'hp_'], 'hp'],
	},
	Furina: {
		key: 'Furina',
		role: 'Off-Field DPS & Support',
		weapon: [
			'SplendorOfTranquilWaters',
			'PrimordialJadeCutter',
			['FesteringDesire', 'KeyOfKhajNisut', 'UrakuMisugiri'],
			['FleuveCendreFerryman', 'FavoniusSword'],
			['WolfFang', 'HaranGeppakuFutsu', 'LightOfFoliarIncision', 'MistsplitterReforged'],
			['SkywardBlade', 'TheDockhandsAssistant', 'HarbingerOfDawn'],
		],
		group: 1,
		artifact: ['GoldenTroupe', 'TenacityOfTheMillelith'],
		mainStat: {
			sands: ['enerRech_', 'hp_'],
			goblet: ['hp_', 'hydro_dmg_'],
			circlet: 'critRD_',
		},
		subStat: ['enerRech_', ['hp_', 'critRD_'], 'hp'],
	},
	Sigewinne: {
		key: 'Sigewinne',
		role: 'Healer',
		weapon: ['SilvershowerHeartstrings', 'RecurveBow', 'FavoniusWarbow', 'ElegyForTheEnd'],
		group: 0,
		artifact: ['SongOfDaysPast', 'OceanHuedClam'],
		mainStat: { sands: 'hp_', goblet: 'hp_', circlet: ['hp_', 'critRate_'] },
		subStat: ['hp_', 'hp', 'critRate_'],
	},
	Mualani: {
		key: 'Mualani',
		role: 'Vaporize DPS',
		weapon: [
			'SurfsUp',
			['SacrificialJade', 'AThousandFloatingDreams'],
			'TomeOfTheEternalFlow',
			['RingOfYaxche', 'TheWidsith'],
		],
		group: 1,
		artifact: ['ObsidianCodex', 'HeartOfDepth', 'MarechausseeHunter'],
		mainStat: {
			sands: ['hp_', 'eleMas'],
			goblet: 'hydro_dmg_',
			circlet: ['critRD_', 'hp_', 'eleMas'],
		},
		subStat: ['critRD_', ['eleMas', 'hp_'], 'hp'],
	},
	// Electro
	Fischl: {
		key: 'Fischl',
		role: 'Off-Field DPS',
		weapon: [
			'PolarStar',
			'AquaSimulacra',
			['SkywardHarp', 'ThunderingPulse', 'HuntersPath'],
			['AmosBow', 'AlleyHunter', 'TheViridescentHunt'],
			'ElegyForTheEnd',
			'FadingTwilight',
			'TheStringless',
			'PrototypeCrescent',
		],
		group: 0,
		artifact: ['GoldenTroupe', 'Thundersoother', 'TenacityOfTheMillelith'],
		mainStat: { sands: 'atk_', goblet: 'electro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'eleMas', 'atk'],
	},
	Beidou: {
		key: 'Beidou',
		role: 'Off-Field DPS',
		weapon: [
			'WolfsGravestone',
			'BeaconOfTheReedSea',
			['TheUnforged', 'SerpentSpine', 'RedhornStonethresher'],
			'Akuoumaru',
			['SkywardPride', 'LuxuriousSeaLord'],
			'PrototypeArchaic',
			'Rainslasher',
		],
		group: 0,
		artifact: ['EmblemOfSeveredFate', 'Thundersoother'],
		mainStat: { sands: ['atk_', 'enerRech_'], goblet: 'electro_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'atk_', 'eleMas', 'atk'],
	},
	Lisa: {
		key: 'Lisa',
		role: 'Aggravate DPS',
		weapon: [
			'KagurasVerity',
			'LostPrayerToTheSacredWinds',
			['SkywardAtlas', 'AThousandFloatingDreams', 'TheWidsith'],
			['TulaytullahsRemembrance', 'SolarPearl', 'MemoryOfDust'],
			'BlackcliffAgate',
			'MappaMare',
			['DodocoTales', 'MagicGuide'],
		],
		group: 0,
		artifact: ['Thundersoother', 'ThunderingFury', 'GildedDreams'],
		mainStat: { sands: ['eleMas', 'atk_'], goblet: 'electro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', ['atk_', 'eleMas'], 'enerRech_', 'atk'],
	},
	Razor: {
		key: 'Razor',
		role: 'Reaction DPS',
		weapon: [
			['MailedFlower', 'MakhairaAquamarine'],
			['Rainslasher', 'BloodtaintedGreatsword'],
			'FavoniusGreatsword',
			'ForestRegalia',
		],
		group: 1,
		artifact: [['GildedDreams', 'FlowerOfParadiseLost'], 'ThunderingFury'],
		mainStat: { sands: 'eleMas', goblet: 'eleMas', circlet: 'eleMas' },
		subStat: ['eleMas', 'enerRech_', 'critRate_'],
	},
	KujouSara: {
		key: 'KujouSara',
		role: 'Support and Damage',
		weapon: [
			'SkywardHarp',
			['PolarStar', 'ElegyForTheEnd'],
			'TheFirstGreatMagic',
			['AquaSimulacra', 'HuntersPath'],
			'ThunderingPulse',
			'AmosBow',
			[
				'FadingTwilight',
				'MouunsMoon',
				'AlleyHunter',
				'TheViridescentHunt',
				'ScionOfTheBlazingSun',
			],
			['SacrificialBow', 'ChainBreaker'],
			'FavoniusWarbow',
		],
		group: 0,
		artifact: ['EmblemOfSeveredFate', 'NoblesseOblige'],
		mainStat: { sands: ['enerRech_', 'atk_'], goblet: 'electro_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'atk_', 'atk'],
	},
	KukiShinobu: {
		key: 'KukiShinobu',
		role: 'Hyperbloom',
		weapon: [
			'FreedomSworn',
			'XiphosMoonlight',
			['IronSting', 'KeyOfKhajNisut', 'ToukabouShigure'],
			['DarkIronSword', 'SapwoodBlade'],
		],
		group: 0,
		artifact: ['FlowerOfParadiseLost', 'GildedDreams', 'ThunderingFury'],
		mainStat: { sands: 'eleMas', goblet: 'eleMas', circlet: 'eleMas' },
		subStat: ['eleMas', 'hp_', 'hp', 'enerRech_'],
	},
	Dori: {
		key: 'Dori',
		role: 'Support',
		weapon: [
			'FavoniusGreatsword',
			'SacrificialGreatsword',
			'KatsuragikiriNagamasa',
			'ForestRegalia',
		],
		group: 1,
		artifact: ['NoblesseOblige', 'DeepwoodMemories', 'Instructor', 'TheExile'],
		mainStat: {
			sands: ['enerRech_', 'hp_', 'eleMas'],
			goblet: ['hp_', 'eleMas'],
			circlet: ['heal_', 'hp_', 'eleMas'],
		},
		subStat: ['critRate_', 'enerRech_', 'hp_', 'eleMas'],
	},
	Sethos: {
		key: 'Sethos',
		role: 'DPS',
		weapon: ['HuntersPath', 'Slingshot'],
		group: 0,
		artifact: ['WanderersTroupe', 'GildedDreams', 'DesertPavilionChronicle'],
		mainStat: { sands: ['eleMas', 'enerRech_'], goblet: 'electro_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'eleMas', 'atk_'],
	},
	Ororon: {
		key: 'Ororon',
		role: 'Off-Field DPS',
		weapon: [
			['PolarStar', 'TheFirstGreatMagic'],
			['ThunderingPulse', 'AquaSimulacra', 'HuntersPath', 'SkywardHarp'],
			'AstralVulturesCrimsonPlumage',
			['ChainBreaker', 'AlleyHunter'],
			['RangeGauge', 'SongOfStillness'],
			['ElegyForTheEnd', 'FadingTwilight'],
			'FavoniusWarbow',
		],
		group: 1,
		artifact: ['ScrollOfTheHeroOfCinderCity', 'NoblesseOblige', 'EmblemOfSeveredFate'],
		mainStat: { sands: ['atk_', 'enerRech_'], goblet: 'electro_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'atk_', 'eleMas'],
	},
	Keqing: {
		key: 'Keqing',
		role: 'Aggravate DPS',
		weapon: [
			'MistsplitterReforged',
			['PrimordialJadeCutter', 'HaranGeppakuFutsu'],
			'FreedomSworn',
			'LightOfFoliarIncision',
			'HarbingerOfDawn',
			'SummitShaper',
			'ToukabouShigure',
			'WolfFang',
			['LionsRoar', 'TheBlackSword'],
			'IronSting',
		],
		group: 0,
		artifact: [['ThunderingFury', 'Thundersoother'], 'GildedDreams'],
		mainStat: { sands: ['atk_', 'eleMas'], goblet: 'electro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', ['atk_', 'eleMas'], 'atk', 'enerRech_'],
	},
	RaidenShogun: {
		key: 'RaidenShogun',
		role: 'DPS',
		weapon: [
			'EngulfingLightning',
			['StaffOfHoma', 'LumidouceElegy', 'PrimordialJadeWingedSpear', 'StaffOfTheScarletSands'],
			'CalamityQueller',
			['TheCatch', 'SkywardSpine', 'VortexVanquisher'],
			'Deathmatch',
			'WavebreakersFin',
			'LithicSpear',
			'FavoniusLance',
			'PrototypeStarglitter',
		],
		group: 0,
		artifact: ['EmblemOfSeveredFate', 'TenacityOfTheMillelith'],
		mainStat: {
			sands: ['enerRech_', 'atk_'],
			goblet: ['electro_dmg_', 'atk_'],
			circlet: 'critRD_',
		},
		subStat: ['critRD_', 'atk_', 'enerRech_', 'eleMas', 'atk'],
	},
	YaeMiko: {
		key: 'YaeMiko',
		role: 'Off-Field Aggravate DPS',
		weapon: [
			'KagurasVerity',
			'AThousandFloatingDreams',
			'TomeOfTheEternalFlow',
			['LostPrayerToTheSacredWinds', 'SkywardAtlas', 'TheWidsith', 'TulaytullahsRemembrance'],
			'SolarPearl',
			'OathswornEye',
			'HakushinRing',
			'MappaMare',
		],
		group: 0,
		artifact: [
			['GildedDreams', 'EmblemOfSeveredFate', 'GoldenTroupe'],
			'Thundersoother',
			'TenacityOfTheMillelith',
		],
		mainStat: {
			sands: ['enerRech_', 'eleMas', 'atk_'],
			goblet: 'electro_dmg_',
			circlet: 'critRD_',
		},
		subStat: ['critRD_', 'eleMas', 'atk_', 'enerRech_', 'atk'],
	},
	Cyno: {
		key: 'Cyno',
		role: 'Quickbloom DPS',
		weapon: [
			'StaffOfTheScarletSands',
			'BalladOfTheFjords',
			'PrimordialJadeWingedSpear',
			'Deathmatch',
			['LumidouceElegy', 'StaffOfHoma', 'WhiteTassel', 'MissiveWindspear'],
			['KitainCrossSpear', 'DragonsBane'],
			'SkywardSpine',
			'FavoniusLance',
		],
		group: 1,
		artifact: [
			'ThunderingFury',
			['GildedDreams', 'FlowerOfParadiseLost'],
			'GladiatorsFinale',
			'MarechausseeHunter',
		],
		mainStat: {
			sands: 'eleMas',
			goblet: ['electro_dmg_', 'eleMas'],
			circlet: ['critRD_', 'eleMas'],
		},
		subStat: ['enerRech_', 'eleMas', 'critRD_', 'atk_'],
	},
	Clorinde: {
		key: 'Clorinde',
		role: 'DPS',
		weapon: [
			'Absolution',
			['LightOfFoliarIncision', 'HaranGeppakuFutsu'],
			['MistsplitterReforged', 'PrimordialJadeCutter', 'UrakuMisugiri', 'FreedomSworn'],
			'CalamityOfEshu',
			['FinaleOfTheDeep', 'TheBlackSword'],
		],
		group: 0,
		artifact: ['FragmentOfHarmonicWhimsy', 'GladiatorsFinale', 'ThunderingFury'],
		mainStat: { sands: ['atk_', 'eleMas'], goblet: 'electro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'eleMas', 'enerRech_'],
	},
	// Cryo
	Diona: {
		key: 'Diona',
		role: 'Support',
		weapon: [
			['FavoniusWarbow', 'SacrificialBow'],
			'ElegyForTheEnd',
			'SilvershowerHeartstrings',
			'RecurveBow',
		],
		group: 1,
		artifact: [
			'NoblesseOblige',
			['MaidenBeloved', 'OceanHuedClam'],
			'Instructor',
			'TenacityOfTheMillelith',
		],
		mainStat: { sands: ['enerRech_', 'hp_'], goblet: 'hp_', circlet: ['hp_', 'heal_'] },
		subStat: ['enerRech_', 'hp_', 'critRate_', 'hp'],
	},
	Chongyun: {
		key: 'Chongyun',
		role: 'Burst Support',
		weapon: [
			'WolfsGravestone',
			'SerpentSpine',
			['RedhornStonethresher', 'BeaconOfTheReedSea'],
			'TheUnforged',
			'SkywardPride',
			'Akuoumaru',
			'LuxuriousSeaLord',
			'LithicBlade',
			'SacrificialGreatsword',
			'BlackcliffSlasher',
			'PrototypeArchaic',
			'FavoniusGreatsword',
		],
		group: 0,
		artifact: [
			'NoblesseOblige',
			['EmblemOfSeveredFate', 'ScrollOfTheHeroOfCinderCity'],
			'GildedDreams',
			'NoblesseOblige',
		],
		mainStat: {
			sands: ['atk_', 'enerRech_', 'eleMas'],
			goblet: 'cryo_dmg_',
			circlet: 'critRD_',
		},
		subStat: ['critRD_', 'atk_', 'eleMas', 'enerRech_', 'atk'],
	},
	Kaeya: {
		key: 'Kaeya',
		role: 'Reverse Melt',
		weapon: [
			'PrimordialJadeCutter',
			'MistsplitterReforged',
			['HaranGeppakuFutsu', 'LightOfFoliarIncision'],
			['FreedomSworn', 'SkywardBlade'],
			'ToukabouShigure',
			['SummitShaper', 'LionsRoar', 'KagotsurubeIsshin', 'AquilaFavonia'],
			['IronSting', 'TheAlleyFlash'],
			'FavoniusSword',
		],
		group: 0,
		artifact: [
			'EmblemOfSeveredFate',
			'Lavawalker',
			'GildedDreams',
			'NoblesseOblige',
			'Instructor',
		],
		mainStat: { sands: ['enerRech_', 'atk_'], goblet: 'cryo_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'atk_', 'eleMas', 'atk'],
	},
	Rosaria: {
		key: 'Rosaria',
		role: 'Freeze',
		weapon: [
			'StaffOfHoma',
			'WavebreakersFin',
			'VortexVanquisher',
			['PrimordialJadeWingedSpear', 'LumidouceElegy'],
			'BlackcliffPole',
			'SkywardSpine',
			'EngulfingLightning',
			'LithicSpear',
			'StaffOfTheScarletSands',
			'TheCatch',
			'Deathmatch',
		],
		group: 0,
		artifact: ['BlizzardStrayer', 'NoblesseOblige'],
		mainStat: { sands: 'atk_', goblet: 'cryo_dmg_', circlet: 'critDMG_' },
		subStat: ['critDMG_', 'atk_', 'enerRech_', 'critRate_', 'atk'],
	},
	Layla: {
		key: 'Layla',
		role: 'Support and Damage',
		weapon: [
			'PrimordialJadeCutter',
			'HarbingerOfDawn',
			['UrakuMisugiri', 'SplendorOfTranquilWaters', 'LightOfFoliarIncision'],
			['MistsplitterReforged', 'WolfFang'],
			'KeyOfKhajNisut',
			'FavoniusSword',
		],
		group: 0,
		artifact: [
			'TenacityOfTheMillelith',
			'BlizzardStrayer',
			'NoblesseOblige',
			'EmblemOfSeveredFate',
		],
		mainStat: {
			sands: ['hp_', 'enerRech_'],
			goblet: ['cryo_dmg_', 'hp_'],
			circlet: ['critRD_', 'hp_'],
		},
		subStat: ['enerRech_', ['critRD_', 'hp_'], 'atk_', 'hp'],
	},
	Mika: {
		key: 'Mika',
		role: 'Support',
		weapon: [
			'FavoniusLance',
			'DialoguesOfTheDesertSages',
			'EngulfingLightning',
			['PrototypeStarglitter', 'TheCatch', 'RightfulReward'],
			'BlackTassel',
		],
		group: 1,
		artifact: ['NoblesseOblige', 'OceanHuedClam', 'MaidenBeloved', 'TheExile'],
		mainStat: { sands: ['enerRech_', 'hp_'], goblet: 'hp_', circlet: ['heal_', 'critRate_'] },
		subStat: ['enerRech_', 'critRate_', 'hp_', 'hp'],
	},
	Freminet: {
		key: 'Freminet',
		role: 'Physical DPS',
		weapon: [
			'SkywardPride',
			['SongOfBrokenPines', 'Verdict', 'WolfsGravestone'],
			['BeaconOfTheReedSea', 'RedhornStonethresher'],
			['SerpentSpine', 'TheUnforged'],
			['PrototypeArchaic', 'TidalShadow', 'SnowTombedStarsilver'],
		],
		group: 1,
		artifact: ['PaleFlame', 'GoldenTroupe', 'GladiatorsFinale'],
		mainStat: { sands: 'atk_', goblet: 'physical_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'atk_', 'eleMas', 'atk'],
	},
	Charlotte: {
		key: 'Charlotte',
		role: 'Support',
		weapon: [
			['PrototypeAmber', 'FavoniusCodex'],
			'ThrillingTalesOfDragonSlayers',
			['OathswornEye', 'WineAndSong'],
		],
		group: 0,
		artifact: [
			['NoblesseOblige', 'TenacityOfTheMillelith'],
			'OceanHuedClam',
			'MaidenBeloved',
			'BlizzardStrayer',
		],
		mainStat: {
			sands: ['enerRech_', 'atk_'],
			goblet: 'atk_',
			circlet: ['heal_', 'atk_', 'critRate_'],
		},
		subStat: ['enerRech_', 'atk_', 'critRate_', 'atk', 'critDMG_'],
	},
	Qiqi: {
		key: 'Qiqi',
		role: 'Support',
		weapon: [
			'SacrificialSword',
			'FavoniusSword',
			'PeakPatrolSong',
			'SkywardBlade',
			'SapwoodBlade',
			'FleuveCendreFerryman',
			'AmenomaKageuchi',
		],
		group: 1,
		artifact: [
			'TenacityOfTheMillelith',
			'ScrollOfTheHeroOfCinderCity',
			['OceanHuedClam', 'SongOfDaysPast'],
		],
		mainStat: { sands: ['atk_', 'enerRech_'], goblet: 'atk_', circlet: ['heal_', 'atk_'] },
		subStat: ['atk_', 'enerRech_', 'atk', 'critRate_', 'def_'],
	},
	Ganyu: {
		key: 'Ganyu',
		role: 'Melt DPS',
		weapon: [
			['HuntersPath', 'TheFirstGreatMagic'],
			['AmosBow', 'AquaSimulacra'],
			['PolarStar', 'SkywardHarp', 'ThunderingPulse'],
			['Hamayumi', 'ScionOfTheBlazingSun'],
			'PrototypeCrescent',
		],
		group: 0,
		artifact: [
			['WanderersTroupe', 'ShimenawasReminiscence'],
			['Lavawalker', 'RetracingBolide'],
			'GildedDreams',
		],
		mainStat: { sands: ['eleMas', 'atk_'], goblet: 'cryo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'eleMas', 'atk_', 'atk'],
	},
	Eula: {
		key: 'Eula',
		role: 'DPS',
		weapon: [
			'SongOfBrokenPines',
			['WolfsGravestone', 'BeaconOfTheReedSea'],
			['SkywardPride', 'Verdict'],
			'TheUnforged',
			'RedhornStonethresher',
			['SerpentSpine', 'UltimateOverlordsMegaMagicSword'],
			['LuxuriousSeaLord', 'Akuoumaru', 'TidalShadow'],
			'LithicBlade',
			'PrototypeArchaic',
			'SnowTombedStarsilver',
			'SkyriderGreatsword',
		],
		group: 0,
		artifact: ['PaleFlame', 'GladiatorsFinale'],
		mainStat: { sands: 'atk_', goblet: 'physical_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'enerRech_', 'atk_', 'atk'],
	},
	KamisatoAyaka: {
		key: 'KamisatoAyaka',
		role: 'DPS',
		weapon: [
			'MistsplitterReforged',
			'HaranGeppakuFutsu',
			['LightOfFoliarIncision', 'PrimordialJadeCutter', 'SummitShaper'],
			'FinaleOfTheDeep',
			['AquilaFavonia', 'SkywardBlade'],
			['AmenomaKageuchi', 'TheBlackSword', 'KagotsurubeIsshin'],
			'HarbingerOfDawn',
		],
		group: 0,
		artifact: ['BlizzardStrayer'],
		mainStat: { sands: 'atk_', goblet: 'cryo_dmg_', circlet: ['critDMG_', 'atk_'] },
		subStat: ['critDMG_', 'atk_', 'enerRech_', 'critRate_', 'atk'],
	},
	Aloy: {
		key: 'Aloy',
		role: 'Burst Support',
		weapon: [
			'ThunderingPulse',
			'PolarStar',
			'SkywardHarp',
			'TheStringless',
			'AmosBow',
			'AlleyHunter',
			'PrototypeCrescent',
			'Predator',
			'SacrificialBow',
			'Slingshot',
		],
		group: 0,
		artifact: ['BlizzardStrayer', 'EmblemOfSeveredFate', 'NoblesseOblige'],
		mainStat: { sands: ['atk_', 'eleMas'], goblet: 'cryo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'eleMas', 'enerRech_', 'atk'],
	},
	Shenhe: {
		key: 'Shenhe',
		role: 'Support',
		weapon: [
			'CalamityQueller',
			'EngulfingLightning',
			'VortexVanquisher',
			'SkywardSpine',
			'FavoniusLance',
			'PrimordialJadeWingedSpear',
			'LithicSpear',
			'StaffOfHoma',
			'WavebreakersFin',
			'MissiveWindspear',
			'PrototypeStarglitter',
		],
		group: 0,
		artifact: ['NoblesseOblige'],
		mainStat: { sands: ['atk_', 'enerRech_'], goblet: 'atk_', circlet: 'atk_' },
		subStat: ['enerRech_', 'atk_', 'critRD_', 'atk'],
	},
	Wriothesley: {
		key: 'Wriothesley',
		role: 'Freeze DPS',
		weapon: [
			['CashflowSupervision', 'TulaytullahsRemembrance'],
			[
				'MemoryOfDust',
				'TomeOfTheEternalFlow',
				'KagurasVerity',
				'LostPrayerToTheSacredWinds',
				'SkywardAtlas',
			],
			['BalladOfTheBoundlessBlue', 'TheWidsith'],
			'FlowingPurity',
		],
		group: 0,
		artifact: ['MarechausseeHunter', ['BlizzardStrayer', 'ShimenawasReminiscence']],
		mainStat: { sands: 'atk_', goblet: 'cryo_dmg_', circlet: 'critDMG_' },
		subStat: ['critRD_', 'atk_', 'atk', 'enerRech_'],
	},
	Citlali: {
		key: 'Citlali',
		role: 'Support',
		weapon: [
			'StarcallersWatch',
			['ThrillingTalesOfDragonSlayers', 'FavoniusCodex', 'WanderingEvenstar'],
		],
		group: 0,
		artifact: ['ScrollOfTheHeroOfCinderCity', 'TenacityOfTheMillelith', 'Instructor'],
		mainStat: {
			sands: ['eleMas', 'enerRech_'],
			goblet: 'eleMas',
			circlet: ['eleMas', 'critRate_'],
		},
		subStat: ['enerRech_', 'eleMas', 'critRate_'],
	},
	// Anemo
	Sucrose: {
		key: 'Sucrose',
		role: 'EM Build',
		weapon: [
			'AThousandFloatingDreams',
			'WanderingEvenstar',
			['SacrificialFragments', 'ThrillingTalesOfDragonSlayers'],
			'HakushinRing',
			'MagicGuide',
			'FavoniusCodex',
		],
		group: 1,
		artifact: ['ViridescentVenerer', 'Instructor'],
		mainStat: { sands: 'eleMas', goblet: 'eleMas', circlet: 'eleMas' },
		subStat: ['eleMas', 'enerRech_', 'atk_', 'critRD_'],
	},
	Sayu: {
		key: 'Sayu',
		role: 'Support',
		weapon: [
			'FavoniusGreatsword',
			'WolfsGravestone',
			'KatsuragikiriNagamasa',
			'SkywardPride',
			'SacrificialGreatsword',
			'MakhairaAquamarine',
			'MailedFlower',
			'ForestRegalia',
			'Rainslasher',
			'BloodtaintedGreatsword',
		],
		group: 0,
		artifact: ['ViridescentVenerer', 'NoblesseOblige', 'OceanHuedClam'],
		mainStat: {
			sands: ['enerRech_', 'eleMas'],
			goblet: ['eleMas', 'atk_'],
			circlet: ['heal_', 'eleMas'],
		},
		subStat: ['enerRech_', 'eleMas', 'atk_', 'critRate_'],
	},
	ShikanoinHeizou: {
		key: 'ShikanoinHeizou',
		role: 'Anemo DPS',
		weapon: [
			['KagurasVerity', 'SkywardAtlas'],
			['LostPrayerToTheSacredWinds', 'CashflowSupervision', 'TomeOfTheEternalFlow'],
			['TulaytullahsRemembrance', 'SolarPearl', 'MemoryOfDust', 'TheWidsith'],
			['MappaMare', 'FlowingPurity'],
			['FavoniusCodex', 'ThrillingTalesOfDragonSlayers', 'HakushinRing', 'PrototypeAmber'],
		],
		group: 1,
		artifact: ['ViridescentVenerer', 'GoldenTroupe', 'DesertPavilionChronicle'],
		mainStat: { sands: 'atk_', goblet: 'anemo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'eleMas'],
	},
	Faruzan: {
		key: 'Faruzan',
		role: 'Support',
		weapon: [
			'FavoniusWarbow',
			'ElegyForTheEnd',
			'EndOfTheLine',
			['FadingTwilight', 'SacrificialBow'],
		],
		group: 0,
		artifact: [
			['ViridescentVenerer', 'NoblesseOblige', 'ScrollOfTheHeroOfCinderCity'],
			'EmblemOfSeveredFate',
			['GoldenTroupe', 'TenacityOfTheMillelith'],
		],
		mainStat: { sands: 'enerRech_', goblet: 'anemo_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRate_', 'critDMG_', 'atk_', 'atk'],
	},
	Lynette: {
		key: 'Lynette',
		role: 'Off-Field DPS',
		weapon: [
			'FavoniusSword',
			['FleuveCendreFerryman', 'SacrificialSword', 'AmenomaKageuchi', 'SkywardBlade'],
			'FreedomSworn',
		],
		group: 0,
		artifact: ['ViridescentVenerer', 'EmblemOfSeveredFate', 'NoblesseOblige'],
		mainStat: { sands: ['enerRech_', 'atk_'], goblet: 'anemo_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRate_', 'critDMG_', 'atk_', 'atk'],
	},
	LanYan: {
		key: 'LanYan',
		role: 'Support',
		weapon: [
			'StarcallersWatch',
			'ThrillingTalesOfDragonSlayers',
			'FavoniusCodex',
			'CranesEchoingCall',
			'HakushinRing',
			'PrototypeAmber',
		],
		group: 0,
		artifact: ['ViridescentVenerer'],
		mainStat: { sands: ['atk_', 'enerRech_'], goblet: 'atk_', circlet: ['atk_', 'critRate_'] },
		subStat: ['enerRech_', 'atk_', 'eleMas', 'critRate_'],
	},
	Jean: {
		key: 'Jean',
		role: 'Support and Damage',
		weapon: [
			'PrimordialJadeCutter',
			'FreedomSworn',
			['MistsplitterReforged', 'HaranGeppakuFutsu'],
			['SkywardBlade', 'FesteringDesire', 'FavoniusSword', 'AmenomaKageuchi'],
			'SummitShaper',
			'AquilaFavonia',
			['TheFlute', 'SapwoodBlade', 'LionsRoar'],
		],
		group: 0,
		artifact: ['ViridescentVenerer', 'NoblesseOblige', 'OceanHuedClam', 'EmblemOfSeveredFate'],
		mainStat: {
			sands: ['atk_', 'enerRech_'],
			goblet: ['anemo_dmg_', 'atk_'],
			circlet: ['critRD_', 'heal_'],
		},
		subStat: ['enerRech_', 'critRD_', 'atk_', 'eleMas', 'atk'],
	},
	Venti: {
		key: 'Venti',
		role: 'Reaction Off-Field DPS',
		weapon: [
			'ElegyForTheEnd',
			['TheStringless', 'Cloudforged'],
			['WindblumeOde', 'PolarStar'],
			'FavoniusWarbow',
			['RavenBow', 'FadingTwilight'],
			['AlleyHunter', 'MouunsMoon'],
			'SongOfStillness',
		],
		group: 1,
		artifact: ['ViridescentVenerer', 'NoblesseOblige', 'GildedDreams'],
		mainStat: { sands: 'eleMas', goblet: 'eleMas', circlet: 'eleMas' },
		subStat: ['eleMas', 'enerRech_', 'atk_', 'critRD_', 'atk'],
	},
	Xiao: {
		key: 'Xiao',
		role: 'DPS',
		weapon: [
			['StaffOfHoma', 'PrimordialJadeWingedSpear', 'LumidouceElegy'],
			'StaffOfTheScarletSands',
			[
				'CalamityQueller',
				'Deathmatch',
				'CrimsonMoonsSemblance',
				'VortexVanquisher',
				'SkywardSpine',
			],
			'BlackcliffPole',
			'LithicSpear',
			['MissiveWindspear', 'ProspectorsDrill', 'WavebreakersFin'],
			'FavoniusLance',
			'WhiteTassel',
		],
		group: 0,
		artifact: ['VermillionHereafter', 'MarechausseeHunter', 'DesertPavilionChronicle'],
		mainStat: { sands: 'atk_', goblet: ['anemo_dmg_', 'atk_'], circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'atk_'],
	},
	KaedeharaKazuha: {
		key: 'KaedeharaKazuha',
		role: 'Reaction DPS & Support',
		weapon: [
			['FreedomSworn', 'XiphosMoonlight'],
			'FavoniusSword',
			[
				'IronSting',
				'ToukabouShigure',
				'SacrificialSword',
				'FleuveCendreFerryman',
				'SapwoodBlade',
				'SkywardBlade',
			],
		],
		group: 0,
		artifact: ['ViridescentVenerer', 'Instructor', 'ThunderingFury'],
		mainStat: { sands: ['eleMas', 'enerRech_'], goblet: 'eleMas', circlet: 'eleMas' },
		subStat: ['enerRech_', 'eleMas', ['atk_', 'critRate_']],
	},
	Wanderer: {
		key: 'Wanderer',
		role: 'DPS',
		weapon: [
			'TulaytullahsRemembrance',
			'LostPrayerToTheSacredWinds',
			'TheWidsith',
			['KagurasVerity', 'TomeOfTheEternalFlow', 'SkywardAtlas', 'MemoryOfDust'],
			['SolarPearl', 'DodocoTales'],
			'BalladOfTheBoundlessBlue',
			'BlackcliffAgate',
			'EyeOfPerception',
			['MappaMare', 'Frostbearer'],
		],
		group: 0,
		artifact: [
			'DesertPavilionChronicle',
			'ShimenawasReminiscence',
			'EchoesOfAnOffering',
			'BlizzardStrayer',
			'Lavawalker',
			'ViridescentVenerer',
		],
		mainStat: { sands: 'atk_', goblet: 'anemo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'atk', 'eleMas', 'enerRech_'],
	},
	Xianyun: {
		key: 'Xianyun',
		role: 'Low Energy Requirement Support',
		weapon: [
			'CranesEchoingCall',
			['SkywardAtlas', 'MemoryOfDust'],
			'CashflowSupervision',
			'ThrillingTalesOfDragonSlayers',
			['FavoniusCodex', 'OathswornEye'],
			'FlowingPurity',
			'WineAndSong',
			['BalladOfTheBoundlessBlue', 'HakushinRing'],
			'Frostbearer',
			'PrototypeAmber',
		],
		group: 0,
		artifact: [
			'ViridescentVenerer',
			'NoblesseOblige',
			['OceanHuedClam', 'SongOfDaysPast', 'ScrollOfTheHeroOfCinderCity'],
		],
		mainStat: { sands: ['atk_', 'enerRech_'], goblet: 'atk_', circlet: 'atk_' },
		subStat: ['enerRech_', 'atk_', 'atk', 'critRate_'],
	},
	Chasca: {
		key: 'Chasca',
		role: 'DPS',
		weapon: [
			'AstralVulturesCrimsonPlumage',
			['AquaSimulacra', 'TheFirstGreatMagic'],
			'ThunderingPulse',
			'SkywardHarp',
			['ChainBreaker', 'SongOfStillness', 'AmosBow', 'PolarStar', 'FlowerWreathedFeathers'],
			['ScionOfTheBlazingSun', 'RangeGauge'],
		],
		group: 0,
		artifact: ['ObsidianCodex', 'MarechausseeHunter'],
		mainStat: { sands: 'atk_', goblet: 'atk_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'eleMas', 'enerRech_'],
	},
	// Geo
	Ningguang: {
		key: 'Ningguang',
		role: 'DPS',
		weapon: [
			'LostPrayerToTheSacredWinds',
			'KagurasVerity',
			'SkywardAtlas',
			'MemoryOfDust',
			'SolarPearl',
			'TheWidsith',
			'FlowingPurity',
			'EyeOfPerception',
			'DodocoTales',
			'WineAndSong',
			'MappaMare',
			'HakushinRing',
		],
		group: 1,
		artifact: [
			'NighttimeWhispersInTheEchoingWoods',
			'HuskOfOpulentDreams',
			['Thundersoother', 'Lavawalker'],
			'ArchaicPetra',
			'EmblemOfSeveredFate',
		],
		mainStat: { sands: 'atk_', goblet: 'geo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'atk'],
	},
	Noelle: {
		key: 'Noelle',
		role: 'DPS',
		weapon: ['RedhornStonethresher', 'SerpentSpine', 'SkywardPride', 'Whiteblind'],
		group: 0,
		artifact: [
			'RetracingBolide',
			'MarechausseeHunter',
			['HuskOfOpulentDreams', 'GladiatorsFinale'],
		],
		mainStat: { sands: ['def_', 'atk_'], goblet: 'geo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'enerRech_', 'def_'],
	},
	Gorou: {
		key: 'Gorou',
		role: 'Support',
		weapon: ['FavoniusWarbow', 'SacrificialBow', 'ElegyForTheEnd'],
		group: 0,
		artifact: ['TheExile', 'NoblesseOblige'],
		mainStat: {
			sands: 'enerRech_',
			goblet: ['geo_dmg_', 'def_'],
			circlet: ['critRate_', 'def_', 'heal_'],
		},
		subStat: ['enerRech_', 'def_', 'critRate_'],
	},
	YunJin: {
		key: 'YunJin',
		role: 'Support',
		weapon: [
			'FavoniusLance',
			'EngulfingLightning',
			['TheCatch', 'PrototypeStarglitter', 'KitainCrossSpear'],
		],
		group: 1,
		artifact: ['HuskOfOpulentDreams', 'NoblesseOblige'],
		mainStat: {
			sands: ['def_', 'enerRech_'],
			goblet: 'def_',
			circlet: ['def_', 'critRate_'],
		},
		subStat: ['def_', 'enerRech_', 'def', 'critRate_'],
	},
	Kachina: {
		key: 'Kachina',
		role: 'Support and Off-Field DPS',
		weapon: [
			'FavoniusLance',
			'FootprintOfTheRainbow',
			'EngulfingLightning',
			'PrototypeStarglitter',
		],
		group: 1,
		artifact: ['ScrollOfTheHeroOfCinderCity'],
		mainStat: {
			sands: ['def_', 'enerRech_'],
			goblet: ['geo_dmg_', 'def_'],
			circlet: ['critRD_'],
		},
		subStat: ['enerRech_', 'critRD_', 'def_'],
	},
	Zhongli: {
		key: 'Zhongli',
		role: 'Shield Support',
		weapon: ['BlackTassel', 'FavoniusLance'],
		group: 0,
		artifact: [
			['ArchaicPetra', 'ScrollOfTheHeroOfCinderCity'],
			['DeepwoodMemories', 'Instructor'],
			'TenacityOfTheMillelith',
		],
		mainStat: { sands: 'hp_', goblet: 'hp_', circlet: ['hp_', 'critRate_'] },
		subStat: ['hp_', 'hp', 'enerRech_'],
	},
	Albedo: {
		key: 'Albedo',
		role: 'Off-Field DPS',
		weapon: [
			['PeakPatrolSong', 'UrakuMisugiri'],
			'CinnabarSpindle',
			['HarbingerOfDawn', 'PrimordialJadeCutter'],
			['LightOfFoliarIncision', 'HaranGeppakuFutsu', 'MistsplitterReforged', 'WolfFang'],
		],
		group: 0,
		artifact: [['HuskOfOpulentDreams', 'GoldenTroupe'], 'ArchaicPetra', 'TenacityOfTheMillelith'],
		mainStat: { sands: 'def_', goblet: ['geo_dmg_', 'def_'], circlet: ['critRD_', 'def_'] },
		subStat: ['critRD_', 'def_', 'atk_', 'enerRech_'],
	},
	AratakiItto: {
		key: 'AratakiItto',
		role: 'DPS',
		weapon: ['RedhornStonethresher', 'SerpentSpine', 'SkywardPride', 'Whiteblind'],
		group: 0,
		artifact: ['HuskOfOpulentDreams', 'DesertPavilionChronicle', 'RetracingBolide'],
		mainStat: { sands: 'def_', goblet: 'geo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'def_', 'enerRech_', 'atk_', 'def', 'atk'],
	},
	Navia: {
		key: 'Navia',
		role: 'DPS',
		weapon: [
			'Verdict',
			'SerpentSpine',
			'BeaconOfTheReedSea',
			'RedhornStonethresher',
			['WolfsGravestone', 'TheUnforged'],
			'SkywardPride',
			'UltimateOverlordsMegaMagicSword',
			'TidalShadow',
			'PrototypeArchaic',
			'KatsuragikiriNagamasa',
		],
		group: 0,
		artifact: ['NighttimeWhispersInTheEchoingWoods', 'GoldenTroupe'],
		mainStat: { sands: ['atk_', 'enerRech_'], goblet: 'geo_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'atk_', 'atk'],
	},
	Chiori: {
		key: 'Chiori',
		role: 'Off-Field DPS',
		weapon: [
			'UrakuMisugiri',
			'PrimordialJadeCutter',
			[
				'HarbingerOfDawn',
				'CinnabarSpindle',
				'LightOfFoliarIncision',
				'HaranGeppakuFutsu',
				'MistsplitterReforged',
				'SplendorOfTranquilWaters',
			],
			'WolfFang',
		],
		group: 0,
		artifact: ['GoldenTroupe', 'HuskOfOpulentDreams'],
		mainStat: { sands: 'def_', goblet: 'geo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'def_', 'atk_', 'def', 'atk', 'enerRech_'],
	},
	Xilonen: {
		key: 'Xilonen',
		role: 'Support',
		weapon: [
			'PeakPatrolSong',
			'FreedomSworn',
			'FavoniusSword',
			'FluteOfEzpitzal',
			'SkyriderSword',
		],
		group: 0,
		artifact: ['ScrollOfTheHeroOfCinderCity', 'ArchaicPetra', 'NoblesseOblige'],
		mainStat: {
			sands: ['def_', 'enerRech_'],
			goblet: 'def_',
			circlet: ['def_', 'heal_', 'critRate_'],
		},
		subStat: ['enerRech_', 'def_', 'def', 'critRate_'],
	},
};
