import type { SlotKey, StatKey } from '@/src/types/good';

export const artifactSlotStats: Record<SlotKey, { name: string; stats: StatKey[] }> = {
	flower: { name: 'Flower', stats: ['hp'] },
	plume: { name: 'Plume', stats: ['atk'] },
	sands: { name: 'Sands', stats: ['hp_', 'atk_', 'def_', 'eleMas', 'enerRech_'] },
	goblet: {
		name: 'Goblet',
		stats: [
			'hp_',
			'atk_',
			'def_',
			'eleMas',
			'pyro_dmg_',
			'electro_dmg_',
			'cryo_dmg_',
			'hydro_dmg_',
			'dendro_dmg_',
			'anemo_dmg_',
			'geo_dmg_',
			'physical_dmg_',
		],
	},
	circlet: {
		name: 'Circlet',
		stats: ['hp_', 'atk_', 'def_', 'eleMas', 'critRate_', 'critDMG_', 'heal_'],
	},
};

export const statName: Record<StatKey, string> = {
	anemo_dmg_: 'Anemo DMG',
	atk: 'ATK',
	atk_: 'ATK %',
	critDMG_: 'Crit DMG',
	critRate_: 'Crit Rate',
	critRD_: 'Crit Rate/DMG',
	cryo_dmg_: 'Cryo DMG',
	def: 'DEF',
	def_: 'DEF %',
	dendro_dmg_: 'Dendro DMG',
	eleMas: 'Elemental Mastery',
	electro_dmg_: 'Electro DMG',
	enerRech_: 'Energy Recharge',
	geo_dmg_: 'Geo DMG',
	heal_: 'Healing Bonus',
	hp: 'HP',
	hp_: 'HP %',
	hydro_dmg_: 'Hydro DMG',
	physical_dmg_: 'Physical DMG',
	pyro_dmg_: 'Pyro DMG',
};

export const subStats: StatKey[] = [
	'hp',
	'hp_',
	'atk',
	'atk_',
	'def',
	'def_',
	'eleMas',
	'enerRech_',
	'critRate_',
	'critDMG_',
];

export const statsMax: Record<StatKey, number> = {
	hp: 1793,
	hp_: 35,
	atk: 117,
	atk_: 35,
	def: 139,
	def_: 43.7,
	eleMas: 140,
	enerRech_: 38.9,
	critRate_: 23.3,
	critDMG_: 46.6,
	critRD_: undefined,
	anemo_dmg_: undefined,
	cryo_dmg_: undefined,
	dendro_dmg_: undefined,
	electro_dmg_: undefined,
	geo_dmg_: undefined,
	heal_: undefined,
	hydro_dmg_: undefined,
	physical_dmg_: undefined,
	pyro_dmg_: undefined,
};

export const statsAverage: Record<StatKey, Record<number, number>> = {
	hp: { 3: 121.89, 4: 203.15, 5: 253.94 },
	hp_: { 3: 2.975, 4: 3.96, 5: 4.955 },
	atk: { 3: 7.94, 4: 13.225, 5: 16.535 },
	atk_: { 3: 2.975, 4: 3.96, 5: 4.955 },
	def: { 3: 9.445, 4: 15.74, 5: 19.675 },
	def_: { 3: 3.715, 4: 4.955, 5: 6.195 },
	eleMas: { 3: 11.89, 4: 15.855, 5: 19.815 },
	enerRech_: { 3: 3.305, 4: 4.405, 5: 5.505 },
	critRate_: { 3: 1.98, 4: 2.645, 5: 3.305 },
	critDMG_: { 3: 3.96, 4: 5.285, 5: 6.605 },
	critRD_: undefined,
	anemo_dmg_: undefined,
	cryo_dmg_: undefined,
	dendro_dmg_: undefined,
	electro_dmg_: undefined,
	geo_dmg_: undefined,
	heal_: undefined,
	hydro_dmg_: undefined,
	physical_dmg_: undefined,
	pyro_dmg_: undefined,
};
