import data from '@/public/data.json';
import type { DCharacter, DElement, Tier } from '@/src/types/data';
import type { CharacterKey } from '@/src/types/good';

export const charactersInfo: Record<CharacterKey, DCharacter> = data.characters as any;

// TODO: update https://docs.google.com/spreadsheets/d/e/2PACX-1vRq-sQxkvdbvaJtQAGG6iVz2q2UN9FCKZ8Mkyis87QHFptcOU3ViLh0_PJyMxFSgwJZrd10kbYpQFl1/pubhtml
// 11/06/23
// Sorted https://genshinlab.com/tier-list
export const charactersTier: Record<CharacterKey, Tier> = {
	Traveler: {
		key: 'Traveler',
		role: 'DPS',
		weapon: ['DullBlade'],
		artifact: ['GladiatorsFinale'],
		mainStat: { sands: 'atk_', goblet: 'atk_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'eleMas', 'atk'],
	},
	// Pyro
	Amber: {
		key: 'Amber',
		role: 'Support',
		weapon: ['ElegyForTheEnd', 'FavoniusWarbow', 'SacrificialBow', 'TheViridescentHunt'],
		artifact: ['NoblesseOblige', 'Instructor', 'TheExile'],
		mainStat: { sands: ['enerRech_', 'atk_'], goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'atk_', 'eleMas', 'atk'],
	},
	Xiangling: {
		key: 'Xiangling',
		role: 'Off-Field DPS',
		weapon: [
			'StaffOfTheScarletSands',
			['StaffOfHoma', 'EngulfingLightning', 'TheCatch'],
			[
				'PrimordialJadeWingedSpear',
				'SkywardSpine',
				'CalamityQueller',
				'Deathmatch',
				'BalladOfTheFjords',
			],
			['VortexVanquisher', 'WavebreakersFin', 'DragonsBane'],
			'MissiveWindspear',
			'KitainCrossSpear',
			'LithicSpear',
			'FavoniusLance',
			'PrototypeStarglitter',
		],
		artifact: ['EmblemOfSeveredFate', 'CrimsonWitchOfFlames', 'NoblesseOblige'],
		mainStat: { sands: ['enerRech_', 'atk_', 'eleMas'], goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'atk_', 'eleMas', 'atk'],
	},
	Bennett: {
		key: 'Bennett',
		role: 'Burst Support',
		weapon: [
			'MistsplitterReforged',
			'AquilaFavonia',
			'SkywardBlade',
			'FreedomSworn',
			'TheAlleyFlash',
			'SapwoodBlade',
			'BlackcliffLongsword',
			'PrototypeRancour',
			'FesteringDesire',
		],
		artifact: ['NoblesseOblige', 'EmblemOfSeveredFate', 'CrimsonWitchOfFlames'],
		mainStat: { sands: ['atk_', 'enerRech_'], goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'eleMas'],
	},
	Xinyan: {
		key: 'Xinyan',
		role: 'Physical DPS',
		weapon: [
			'RedhornStonethresher',
			'SkywardPride',
			'SerpentSpine',
			'TheUnforged',
			'SongOfBrokenPines',
			'WolfsGravestone',
			'LuxuriousSeaLord',
			'SnowTombedStarsilver',
			'PrototypeArchaic',
		],
		artifact: ['PaleFlame'],
		mainStat: { sands: ['atk_', 'enerRech_'], goblet: 'physical_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'def_'],
	},
	Yanfei: {
		key: 'Yanfei',
		role: 'DPS',
		weapon: [
			['SkywardAtlas', 'MemoryOfDust'],
			'LostPrayerToTheSacredWinds',
			'KagurasVerity',
			'TheWidsith',
			'DodocoTales',
			'SolarPearl',
			'BlackcliffAgate',
			'MappaMare',
		],
		artifact: [
			'CrimsonWitchOfFlames',
			'GildedDreams',
			'WanderersTroupe',
			'ShimenawasReminiscence',
			'RetracingBolide',
		],
		mainStat: { sands: ['atk_', 'eleMas'], goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'eleMas', 'atk'],
	},
	Thoma: {
		key: 'Thoma',
		role: 'Burgeon',
		weapon: ['KitainCrossSpear', 'FavoniusLance', 'DragonsBane', 'Moonpiercer', 'BlackTassel'],
		artifact: ['FlowerOfParadiseLost', 'GildedDreams', 'CrimsonWitchOfFlames'],
		mainStat: { sands: ['enerRech_', 'eleMas'], goblet: 'eleMas', circlet: 'eleMas' },
		subStat: ['enerRech_', 'eleMas', 'hp_', 'hp', 'critRate_'],
	},
	Diluc: {
		key: 'Diluc',
		role: 'DPS',
		weapon: [
			['RedhornStonethresher', 'BeaconOfTheReedSea'],
			'SerpentSpine',
			['WolfsGravestone', 'TheUnforged'],
			['Rainslasher', 'MailedFlower'],
			'SkywardPride',
			'SongOfBrokenPines',
			['BlackcliffSlasher', 'LuxuriousSeaLord'],
			'PrototypeArchaic',
		],
		artifact: ['CrimsonWitchOfFlames', 'GildedDreams', 'GladiatorsFinale'],
		mainStat: { sands: ['eleMas', 'atk_'], goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'eleMas', 'enerRech_'],
	},
	Klee: {
		key: 'Klee',
		role: 'DPS',
		weapon: [
			'TheWidsith',
			['LostPrayerToTheSacredWinds', 'KagurasVerity'],
			['SkywardAtlas', 'TulaytullahsRemembrance'],
			'MemoryOfDust',
			'SolarPearl',
			'DodocoTales',
			'BlackcliffAgate',
			'MappaMare',
			'MagicGuide',
		],
		artifact: ['Lavawalker', 'CrimsonWitchOfFlames', 'WanderersTroupe'],
		mainStat: { sands: 'atk_', goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'eleMas', 'enerRech_', 'atk'],
	},
	HuTao: {
		key: 'HuTao',
		role: 'DPS',
		weapon: [
			'StaffOfHoma',
			'StaffOfTheScarletSands',
			'BalladOfTheFjords',
			['DragonsBane', 'Deathmatch'],
			'PrimordialJadeWingedSpear',
			'LithicSpear',
			'MissiveWindspear',
			['WhiteTassel', 'BlackcliffPole', 'KitainCrossSpear', 'RightfulReward'],
		],
		artifact: [
			'CrimsonWitchOfFlames',
			'ShimenawasReminiscence',
			'GildedDreams',
			'RetracingBolide',
		],
		mainStat: { sands: ['hp_', 'eleMas'], goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'eleMas', 'hp_', 'atk_', 'enerRech_'],
	},
	Yoimiya: {
		key: 'Yoimiya',
		role: 'DPS',
		weapon: [
			'ThunderingPulse',
			['AquaSimulacra', 'PolarStar'],
			'HuntersPath',
			'Slingshot',
			['AmosBow', 'SkywardHarp'],
			'Rust',
		],
		artifact: [
			'ShimenawasReminiscence',
			'CrimsonWitchOfFlames',
			'GildedDreams',
			'EchoesOfAnOffering',
			'RetracingBolide',
		],
		mainStat: { sands: ['atk_', 'eleMas'], goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'eleMas', 'enerRech_', 'atk'],
	},
	Dehya: {
		key: 'Dehya',
		role: 'Support',
		weapon: [
			'FavoniusGreatsword',
			['WolfsGravestone', 'MakhairaAquamarine'],
			'TheBell',
			'PrototypeArchaic',
		],
		artifact: [
			'TenacityOfTheMillelith',
			'Instructor',
			'OceanHuedClam',
			'MaidenBeloved',
			'DeepwoodMemories',
		],
		mainStat: { sands: 'hp_', goblet: 'hp_', circlet: ['hp_', 'critRate_'] },
		subStat: ['hp_', 'hp', 'eleMas', 'atk_', 'atk'],
	},
	Lyney: {
		key: 'Lyney',
		role: 'DPS',
		weapon: [
			'TheFirstGreatMagic',
			'AquaSimulacra',
			'ThunderingPulse',
			'SkywardHarp',
			'AmosBow',
			['PolarStar', 'SongOfStillness', 'PrototypeCrescent'],
			['ScionOfTheBlazingSun', 'BlackcliffWarbow'],
		],
		artifact: [
			'MarechausseeHunter',
			['Lavawalker', 'VermillionHereafter', 'ShimenawasReminiscence'],
			['RetracingBolide', 'DesertPavilionChronicle'],
			'WanderersTroupe',
		],
		mainStat: { sands: 'atk_', goblet: 'pyro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'atk'],
	},
	// Dendro
	Collei: {
		key: 'Collei',
		role: 'Support',
		weapon: ['ElegyForTheEnd', 'PolarStar', 'SacrificialBow', 'FavoniusWarbow'],
		artifact: [
			'DeepwoodMemories',
			'NoblesseOblige',
			'TenacityOfTheMillelith',
			'Instructor',
			'GildedDreams',
			'TheExile',
		],
		mainStat: {
			sands: ['enerRech_', 'atk_', 'eleMas'],
			goblet: ['dendro_dmg_', 'eleMas'],
			circlet: ['critRD_', 'eleMas'],
		},
		subStat: ['enerRech_', 'critRD_', ['atk_', 'eleMas']],
	},
	Yaoyao: {
		key: 'Yaoyao',
		role: 'Support',
		weapon: [
			'FavoniusLance',
			['BlackTassel', 'RightfulReward'],
			'Moonpiercer',
			'KitainCrossSpear',
		],
		artifact: [
			'DeepwoodMemories',
			'TenacityOfTheMillelith',
			'Instructor',
			'OceanHuedClam',
			'MaidenBeloved',
			'FlowerOfParadiseLost',
			'GildedDreams',
		],
		mainStat: { sands: ['hp_', 'enerRech_'], goblet: 'hp_', circlet: 'heal_' },
		subStat: ['enerRech_', 'hp_', 'critRate_', 'hp'],
	},
	Kaveh: {
		key: 'Kaveh',
		role: 'Bloom Driver',
		weapon: [
			'FavoniusGreatsword',
			'SacrificialGreatsword',
			'MailedFlower',
			['WolfsGravestone', 'SongOfBrokenPines'],
			['MakhairaAquamarine', 'KatsuragikiriNagamasa'],
			['SkywardPride', 'ForestRegalia', 'Rainslasher'],
		],
		artifact: [
			'DeepwoodMemories',
			'OceanHuedClam',
			'FlowerOfParadiseLost',
			'Instructor',
			'GildedDreams',
		],
		mainStat: {
			sands: ['enerRech_', 'eleMas'],
			goblet: 'eleMas',
			circlet: ['eleMas', 'critRate_'],
		},
		subStat: ['enerRech_', 'eleMas', 'critRate_'],
	},
	Kirara: {
		key: 'Kirara',
		role: 'Shield Support',
		weapon: [
			['FavoniusSword', 'KeyOfKhajNisut'],
			'TheDockhandsAssistant',
			'SacrificialSword',
			['SapwoodBlade', 'FesteringDesire', 'FreedomSworn'],
			'PrimordialJadeCutter',
		],
		artifact: ['Instructor', 'TenacityOfTheMillelith', 'DeepwoodMemories', 'NoblesseOblige'],
		mainStat: { sands: ['hp_', 'enerRech_'], goblet: 'hp_', circlet: ['hp_', 'critRate_'] },
		subStat: ['enerRech_', 'hp_', 'critRate_', 'hp'],
	},
	Tighnari: {
		key: 'Tighnari',
		role: 'Quick Swap DPS',
		weapon: [
			'HuntersPath',
			['AquaSimulacra', 'PolarStar', 'TheFirstGreatMagic', 'ElegyForTheEnd'],
			['SkywardHarp', 'ThunderingPulse'],
			'AmosBow',
			['ScionOfTheBlazingSun', 'FadingTwilight'],
			'TheViridescentHunt',
			['Slingshot', 'RangeGuage', 'WindblumeOde', 'SongOfStillness'],
			['PrototypeCrescent', 'IbisPiercer'],
		],
		artifact: [['WanderersTroupe', 'GildedDreams'], 'DeepwoodMemories'],
		mainStat: { sands: ['atk_', 'eleMas'], goblet: 'dendro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'eleMas', 'atk_', 'enerRech_'],
	},
	Nahida: {
		key: 'Nahida',
		role: 'DPS & Support',
		weapon: [
			'AThousandFloatingDreams',
			'KagurasVerity',
			'SacrificialFragments',
			'WanderingEvenstar',
			'TheWidsith',
			['SkywardAtlas', 'LostPrayerToTheSacredWinds', 'MemoryOfDust', 'SolarPearl'],
			'FavoniusCodex',
			['MappaMare', 'MagicGuide', 'HakushinRing'],
			'ThrillingTalesOfDragonSlayers',
			'PrototypeAmber',
		],
		artifact: [
			'DeepwoodMemories',
			'GildedDreams',
			'TenacityOfTheMillelith',
			'FlowerOfParadiseLost',
		],
		mainStat: {
			sands: 'eleMas',
			goblet: ['eleMas', 'dendro_dmg_'],
			circlet: ['eleMas', 'critRD_'],
		},
		subStat: ['enerRech_', ['critRD_', 'eleMas'], 'atk_'],
	},
	Alhaitham: {
		key: 'Alhaitham',
		role: 'Spread DPS',
		weapon: [
			'LightOfFoliarIncision',
			'PrimordialJadeCutter',
			['MistsplitterReforged', 'HaranGeppakuFutsu'],
			'FreedomSworn',
			'WolfFang',
			'ToukabouShigure',
			'TheBlackSword',
			['SummitShaper', 'IronSting', 'BlackcliffLongsword', 'HarbingerOfDawn'],
			['XiphosMoonlight', 'FesteringDesire'],
			'SkywardBlade',
		],
		artifact: ['GildedDreams', 'DeepwoodMemories'],
		mainStat: { sands: ['eleMas', 'atk_'], goblet: 'dendro_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'eleMas', 'atk_', 'atk'],
	},
	Baizhu: {
		key: 'Baizhu',
		role: 'Support',
		weapon: [
			'JadefallsSplendor',
			'PrototypeAmber',
			'FavoniusCodex',
			'HakushinRing',
			'ThrillingTalesOfDragonSlayers',
		],
		artifact: ['DeepwoodMemories', 'OceanHuedClam', 'Instructor', 'NoblesseOblige'],
		mainStat: { sands: ['hp_', 'enerRech_'], goblet: 'hp_', circlet: 'hp_' },
		subStat: ['enerRech_', 'hp_', 'hp'],
	},
	// Hydro
	Xingqiu: {
		key: 'Xingqiu',
		role: 'Off-Field DPS',
		weapon: [
			'PrimordialJadeCutter',
			'MistsplitterReforged',
			'HaranGeppakuFutsu',
			'LightOfFoliarIncision',
			['SkywardBlade', 'WolfFang'],
			'SummitShaper',
			['FavoniusSword', 'FleuveCendreFerryman'],
			'FinaleOfTheDeep',
			['FesteringDesire', 'SacrificialSword', 'AmenomaKageuchi', 'HarbingerOfDawn'],
			['SapwoodBlade', 'FreedomSworn', 'LionsRoar'],
		],
		artifact: ['EmblemOfSeveredFate', 'NoblesseOblige', 'NymphsDream', 'BlizzardStrayer'],
		mainStat: { sands: ['enerRech_', 'atk_'], goblet: 'hydro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'eleMas', 'atk'],
	},
	Barbara: {
		key: 'Barbara',
		role: 'Support',
		weapon: [
			'ThrillingTalesOfDragonSlayers',
			'EverlastingMoonglow',
			'PrototypeAmber',
			'FavoniusCodex',
		],
		artifact: [['MaidenBeloved', 'OceanHuedClam'], 'Instructor'],
		mainStat: { sands: 'hp_', goblet: 'hp_', circlet: 'heal_' },
		subStat: ['hp_', 'hp_'],
	},
	Candace: {
		key: 'Candace',
		role: 'Support',
		weapon: [
			'FavoniusLance',
			'EngulfingLightning',
			['StaffOfHoma', 'Deathmatch', 'TheCatch'],
			'PrototypeStarglitter',
			'SerpentSpine',
			'BlackTassel',
		],
		artifact: ['EmblemOfSeveredFate'],
		mainStat: {
			sands: ['enerRech_', 'hp_'],
			goblet: ['hp_', 'hydro_dmg_'],
			circlet: ['hp_', 'critRD_'],
		},
		subStat: ['enerRech_', 'critRate_', 'hp_', 'hp'],
	},
	Tartaglia: {
		key: 'Tartaglia',
		role: 'DPS',
		weapon: [
			'PolarStar',
			['ThunderingPulse', 'HuntersPath', 'AquaSimulacra'],
			'SkywardHarp',
			'AmosBow',
			'TheViridescentHunt',
			'BlackcliffWarbow',
			['MouunsMoon', 'PrototypeCrescent'],
			['Rust', 'KingsSquire', 'Hamayumi', 'TheStringless'],
			'Slingshot',
		],
		artifact: ['NymphsDream', 'HeartOfDepth', 'ShimenawasReminiscence'],
		mainStat: { sands: 'atk_', goblet: 'hydro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'eleMas', 'enerRech_', 'atk'],
	},
	Mona: {
		key: 'Mona',
		role: 'Burst Support',
		weapon: [
			'ThrillingTalesOfDragonSlayers',
			'FavoniusCodex',
			'AThousandFloatingDreams',
			'PrototypeAmber',
			'WineAndSong',
		],
		artifact: ['NoblesseOblige', 'Instructor', 'TenacityOfTheMillelith'],
		mainStat: {
			sands: ['enerRech_', 'atk_'],
			goblet: ['hydro_dmg_', 'atk_'],
			circlet: 'critRate_',
		},
		subStat: ['enerRech_', 'critRate_', 'atk_'],
	},
	SangonomiyaKokomi: {
		key: 'SangonomiyaKokomi',
		role: 'Support',
		weapon: [
			'ThrillingTalesOfDragonSlayers',
			'PrototypeAmber',
			'HakushinRing',
			'SacrificialFragments',
		],
		artifact: [['OceanHuedClam', 'TenacityOfTheMillelith'], 'MaidenBeloved'],
		mainStat: { sands: ['enerRech_', 'hp_'], goblet: 'hp_', circlet: ['heal_', 'hp_'] },
		subStat: ['enerRech_', 'hp_', 'atk_', 'hp', 'atk'],
	},
	KamisatoAyato: {
		key: 'KamisatoAyato',
		role: 'DPS',
		weapon: [
			['HaranGeppakuFutsu', 'PrimordialJadeCutter'],
			'MistsplitterReforged',
			'TheBlackSword',
			'SummitShaper',
			'FinaleOfTheDeep',
			'KagotsurubeIsshin',
			'LionsRoar',
			['AmenomaKageuchi', 'SkywardBlade'],
		],
		artifact: [
			['HeartOfDepth', 'GladiatorsFinale', 'NymphsDream'],
			'BlizzardStrayer',
			'ThunderingFury',
			'EchoesOfAnOffering',
		],
		mainStat: { sands: 'atk_', goblet: 'hydro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'hp_', 'eleMas', 'atk'],
	},
	Yelan: {
		key: 'Yelan',
		role: 'Off-Field DPS',
		weapon: ['ElegyForTheEnd', 'FavoniusWarbow', 'AquaSimulacra', 'SacrificialBow'],
		artifact: ['EmblemOfSeveredFate'],
		mainStat: {
			sands: ['enerRech_', 'hp_'],
			goblet: ['hydro_dmg_', 'hp_'],
			circlet: ['critRD_', 'hp_'],
		},
		subStat: ['enerRech_', ['hp_', 'critRD_'], 'hp'],
	},
	Nilou: {
		key: 'Nilou',
		role: 'Bloom Support',
		weapon: [
			'KeyOfKhajNisut',
			'TheDockhandsAssistant',
			['FreedomSworn', 'XiphosMoonlight'],
			['IronSting', 'ToukabouShigure'],
			['FavoniusSword', 'FesteringDesire', 'SacrificialSword', 'SapwoodBlade'],
			'PrimordialJadeCutter',
		],
		artifact: ['DeepwoodMemories'],
		mainStat: { sands: ['hp_', 'enerRech_'], goblet: 'hp_', circlet: 'hp_' },
		subStat: ['hp_', 'hp', 'enerRech_', 'eleMas', 'critRD_'],
	},
	Neuvillette: {
		key: 'Neuvillette',
		role: 'DPS',
		weapon: [
			'TomeOfTheEternalFlow',
			'SacrificialJade',
			['JadefallsSplendor', 'PrototypeAmber', 'KagurasVerity', 'LostPrayerToTheSacredWinds'],
		],
		artifact: [
			'MarechausseeHunter',
			'HeartOfDepth',
			['RetracingBolide', 'WanderersTroupe', 'NymphsDream'],
		],
		mainStat: { sands: 'hp_', goblet: ['hydro_dmg_', 'hp_'], circlet: ['critRD_', 'hp_'] },
		subStat: ['enerRech_', ['critRD_', 'hp_'], 'hp'],
	},
	// Electro
	Fischl: {
		key: 'Fischl',
		role: 'Off-Field DPS',
		weapon: [
			'PolarStar',
			'AquaSimulacra',
			['SkywardHarp', 'ThunderingPulse', 'HuntersPath'],
			['AmosBow', 'AlleyHunter', 'TheViridescentHunt'],
			'ElegyForTheEnd',
			'FadingTwilight',
			'TheStringless',
			'PrototypeCrescent',
		],
		artifact: ['GoldenTroupe', 'Thundersoother', 'TenacityOfTheMillelith'],
		mainStat: { sands: 'atk_', goblet: 'electro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'eleMas', 'atk'],
	},
	Beidou: {
		key: 'Beidou',
		role: 'Off-Field DPS',
		weapon: [
			'WolfsGravestone',
			'BeaconOfTheReedSea',
			['TheUnforged', 'SerpentSpine', 'RedhornStonethresher'],
			'Akuoumaru',
			['SkywardPride', 'LuxuriousSeaLord'],
			'PrototypeArchaic',
			'Rainslasher',
		],
		artifact: ['EmblemOfSeveredFate', 'Thundersoother'],
		mainStat: { sands: ['atk_', 'enerRech_'], goblet: 'electro_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'atk_', 'eleMas', 'atk'],
	},
	Lisa: {
		key: 'Lisa',
		role: 'Aggravate DPS',
		weapon: [
			'KagurasVerity',
			'LostPrayerToTheSacredWinds',
			['SkywardAtlas', 'AThousandFloatingDreams', 'TheWidsith'],
			['TulaytullahsRemembrance', 'SolarPearl', 'MemoryOfDust'],
			'BlackcliffAgate',
			'MappaMare',
			['DodocoTales', 'MagicGuide'],
		],
		artifact: ['ThunderingFury', 'GildedDreams', 'Thundersoother'],
		mainStat: { sands: ['eleMas', 'atk_'], goblet: 'electro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', ['atk_', 'eleMas'], 'enerRech_', 'atk'],
	},
	Razor: {
		key: 'Razor',
		role: 'Hyperbloom/EM Build',
		weapon: [
			['MailedFlower', 'MakhairaAquamarine'],
			['Rainslasher', 'BloodtaintedGreatsword'],
			'FavoniusGreatsword',
			'ForestRegalia',
		],
		artifact: [['GildedDreams', 'FlowerOfParadiseLost'], 'ThunderingFury'],
		mainStat: { sands: 'eleMas', goblet: 'eleMas', circlet: 'eleMas' },
		subStat: ['eleMas', 'enerRech_', 'critRate_'],
	},
	KujouSara: {
		key: 'KujouSara',
		role: 'Burst Support',
		weapon: [
			'PolarStar',
			'SkywardHarp',
			['HuntersPath', 'AquaSimulacra'],
			'ThunderingPulse',
			['AmosBow', 'MouunsMoon'],
			'ElegyForTheEnd',
			['AlleyHunter', 'FadingTwilight'],
			'TheViridescentHunt',
			'BlackcliffWarbow',
			'SacrificialBow',
			'PrototypeCrescent',
			'FavoniusWarbow',
			'Messenger',
		],
		artifact: ['EmblemOfSeveredFate', 'NoblesseOblige'],
		mainStat: { sands: ['enerRech_', 'atk_'], goblet: 'electro_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'atk_', 'atk'],
	},
	KukiShinobu: {
		key: 'KukiShinobu',
		role: 'Hyperbloom',
		weapon: [
			'FreedomSworn',
			'XiphosMoonlight',
			['IronSting', 'KeyOfKhajNisut', 'ToukabouShigure'],
			['DarkIronSword', 'SapwoodBlade'],
		],
		artifact: ['FlowerOfParadiseLost', 'GildedDreams', 'ThunderingFury'],
		mainStat: { sands: 'eleMas', goblet: 'eleMas', circlet: 'eleMas' },
		subStat: ['eleMas', 'hp_', 'hp', 'enerRech_'],
	},
	Dori: {
		key: 'Dori',
		role: 'Support',
		weapon: [
			'FavoniusGreatsword',
			'SacrificialGreatsword',
			'KatsuragikiriNagamasa',
			'ForestRegalia',
		],
		artifact: ['NoblesseOblige', 'DeepwoodMemories', 'Instructor', 'TheExile'],
		mainStat: {
			sands: ['enerRech_', 'hp_', 'eleMas'],
			goblet: ['hp_', 'eleMas'],
			circlet: ['heal_', 'hp_', 'eleMas'],
		},
		subStat: ['critRate_', 'enerRech_', 'hp_', 'eleMas'],
	},
	Keqing: {
		key: 'Keqing',
		role: 'Aggravate DPS',
		weapon: [
			'MistsplitterReforged',
			['PrimordialJadeCutter', 'HaranGeppakuFutsu'],
			'FreedomSworn',
			'LightOfFoliarIncision',
			'HarbingerOfDawn',
			'SummitShaper',
			'ToukabouShigure',
			'WolfFang',
			['LionsRoar', 'TheBlackSword'],
			'IronSting',
		],
		artifact: [['Thundersoother', 'ThunderingFury'], 'GildedDreams'],
		mainStat: { sands: ['atk_', 'eleMas'], goblet: 'electro_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', ['atk_', 'eleMas'], 'atk', 'enerRech_'],
	},
	RaidenShogun: {
		key: 'RaidenShogun',
		role: 'DPS',
		weapon: [
			'EngulfingLightning',
			['StaffOfHoma', 'PrimordialJadeWingedSpear', 'StaffOfTheScarletSands'],
			'CalamityQueller',
			['TheCatch', 'SkywardSpine'],
			'VortexVanquisher',
			'Deathmatch',
			'WavebreakersFin',
			'LithicSpear',
			'FavoniusLance',
			'PrototypeStarglitter',
		],
		artifact: ['EmblemOfSeveredFate', 'TenacityOfTheMillelith'],
		mainStat: {
			sands: ['enerRech_', 'atk_'],
			goblet: ['electro_dmg_', 'atk_'],
			circlet: 'critRD_',
		},
		subStat: ['critRD_', 'atk_', 'enerRech_', 'eleMas', 'atk'],
	},
	YaeMiko: {
		key: 'YaeMiko',
		role: 'Off-Field Aggravate DPS',
		weapon: [
			'KagurasVerity',
			'AThousandFloatingDreams',
			'TomeOfTheEternalFlow',
			['LostPrayerToTheSacredWinds', 'SkywardAtlas', 'TheWidsith', 'TulaytullahsRemembrance'],
			'SolarPearl',
			'OathswornEye',
			'HakushinRing',
			'MappaMare',
		],
		artifact: [
			['GoldenTroupe', 'EmblemOfSeveredFate', 'GildedDreams'],
			'Thundersoother',
			'TenacityOfTheMillelith',
		],
		mainStat: {
			sands: ['enerRech_', 'eleMas', 'atk_'],
			goblet: 'electro_dmg_',
			circlet: 'critRD_',
		},
		subStat: ['critRD_', 'eleMas', 'atk_', 'enerRech_', 'atk'],
	},
	Cyno: {
		key: 'Cyno',
		role: 'Quickbloom DPS',
		weapon: [
			'StaffOfTheScarletSands',
			['BalladOfTheFjords', 'DragonsBane'],
			'PrimordialJadeWingedSpear',
			['WhiteTassel', 'MissiveWindspear', 'KitainCrossSpear', 'Deathmatch', 'StaffOfHoma'],
			'Moonpiercer',
			'EngulfingLightning',
			'PrototypeStarglitter',
			'FavoniusLance',
		],
		artifact: ['ThunderingFury', 'GildedDreams', 'GladiatorsFinale', 'FlowerOfParadiseLost'],
		mainStat: {
			sands: 'eleMas',
			goblet: ['electro_dmg_', 'eleMas'],
			circlet: ['critRD_', 'eleMas'],
		},
		subStat: ['enerRech_', 'eleMas', 'critRD_', 'atk_'],
	},
	// Cryo
	Diona: {
		key: 'Diona',
		role: 'Support',
		weapon: [['FavoniusWarbow', 'SacrificialBow'], 'ElegyForTheEnd', 'RecurveBow'],
		artifact: [
			'NoblesseOblige',
			['MaidenBeloved', 'OceanHuedClam'],
			'Instructor',
			'TenacityOfTheMillelith',
		],
		mainStat: { sands: ['enerRech_', 'hp_'], goblet: 'hp_', circlet: ['hp_', 'heal_'] },
		subStat: ['enerRech_', 'hp_', 'critRate_', 'hp'],
	},
	Chongyun: {
		key: 'Chongyun',
		role: 'Burst Support',
		weapon: [
			'WolfsGravestone',
			'SerpentSpine',
			['RedhornStonethresher', 'BeaconOfTheReedSea'],
			'TheUnforged',
			'SkywardPride',
			'Akuoumaru',
			'LuxuriousSeaLord',
			'LithicBlade',
			'SacrificialGreatsword',
			'BlackcliffSlasher',
			'PrototypeArchaic',
			'FavoniusGreatsword',
		],
		artifact: ['EmblemOfSeveredFate', 'GildedDreams', 'NoblesseOblige'],
		mainStat: { sands: ['atk_', 'enerRech_', 'eleMas'], goblet: 'cryo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'eleMas', 'enerRech_', 'atk'],
	},
	Kaeya: {
		key: 'Kaeya',
		role: 'Reverse Melt',
		weapon: [
			'PrimordialJadeCutter',
			'MistsplitterReforged',
			['LightOfFoliarIncision', 'FreedomSworn'],
			['SkywardBlade', 'HaranGeppakuFutsu'],
			'SummitShaper',
			'AquilaFavonia',
			'LionsRoar',
			'KagotsurubeIsshin',
			['TheAlleyFlash', 'IronSting'],
			'AmenomaKageuchi',
		],
		artifact: ['EmblemOfSeveredFate', 'NoblesseOblige', 'Instructor'],
		mainStat: { sands: ['enerRech_', 'atk_'], goblet: 'cryo_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'atk_', 'eleMas', 'atk'],
	},
	Rosaria: {
		key: 'Rosaria',
		role: 'Freeze',
		weapon: [
			'StaffOfHoma',
			'WavebreakersFin',
			'VortexVanquisher',
			'PrimordialJadeWingedSpear',
			'BlackcliffPole',
			'SkywardSpine',
			'EngulfingLightning',
			'LithicSpear',
			'StaffOfTheScarletSands',
			'TheCatch',
			'Deathmatch',
		],
		artifact: ['BlizzardStrayer', 'NoblesseOblige'],
		mainStat: { sands: 'atk_', goblet: 'cryo_dmg_', circlet: 'critDMG_' },
		subStat: ['critDMG_', 'atk_', 'enerRech_', 'critRate_', 'atk'],
	},
	Layla: {
		key: 'Layla',
		role: 'Support',
		weapon: [
			'KeyOfKhajNisut',
			'TheDockhandsAssistant',
			'PrimordialJadeCutter',
			'FavoniusSword',
			'FreedomSworn',
			'HarbingerOfDawn',
		],
		artifact: [
			'TenacityOfTheMillelith',
			'NoblesseOblige',
			'BlizzardStrayer',
			'EmblemOfSeveredFate',
		],
		mainStat: {
			sands: ['hp_', 'enerRech_'],
			goblet: ['hp_', 'cryo_dmg_'],
			circlet: ['hp_', 'critRD_'],
		},
		subStat: ['hp_', 'enerRech_', 'critRD_'],
	},
	Mika: {
		key: 'Mika',
		role: 'Support',
		weapon: [
			'FavoniusLance',
			'EngulfingLightning',
			['PrototypeStarglitter', 'TheCatch', 'RightfulReward'],
			'BlackTassel',
		],
		artifact: ['NoblesseOblige', 'OceanHuedClam', 'MaidenBeloved', 'TheExile'],
		mainStat: { sands: ['enerRech_', 'hp_'], goblet: 'hp_', circlet: ['heal_', 'critRate_'] },
		subStat: ['enerRech_', 'critRate_', 'hp_', 'hp'],
	},
	Freminet: {
		key: 'Freminet',
		role: 'Physical DPS',
		weapon: [
			'SkywardPride',
			['SongOfBrokenPines', 'WolfsGravestone'],
			['BeaconOfTheReedSea', 'RedhornStonethresher'],
			['SerpentSpine', 'TheUnforged'],
			['PrototypeArchaic', 'TidalShadow', 'SnowTombedStarsilver'],
		],
		artifact: ['PaleFlame', 'GoldenTroupe', 'GladiatorsFinale'],
		mainStat: { sands: 'atk_', goblet: 'physical_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'atk_', 'eleMas', 'atk'],
	},
	Qiqi: {
		key: 'Qiqi',
		role: 'Support',
		weapon: [
			'SacrificialSword',
			'SkywardBlade',
			'KagotsurubeIsshin',
			'TheFlute',
			'FavoniusSword',
			'FesteringDesire',
			'AmenomaKageuchi',
			'SkyriderSword',
		],
		artifact: ['TenacityOfTheMillelith', 'OceanHuedClam', 'MaidenBeloved', 'NoblesseOblige'],
		mainStat: { sands: ['atk_', 'enerRech_'], goblet: 'atk_', circlet: ['heal_', 'atk_'] },
		subStat: ['atk_', 'enerRech_', 'atk'],
	},
	Ganyu: {
		key: 'Ganyu',
		role: 'Melt DPS',
		weapon: [
			['HuntersPath', 'TheFirstGreatMagic'],
			['AmosBow', 'AquaSimulacra'],
			['PolarStar', 'SkywardHarp', 'ThunderingPulse'],
			['Hamayumi', 'ScionOfTheBlazingSun'],
			'PrototypeCrescent',
		],
		artifact: [
			['WanderersTroupe', 'ShimenawasReminiscence'],
			['Lavawalker', 'RetracingBolide'],
			'GildedDreams',
		],
		mainStat: { sands: ['eleMas', 'atk_'], goblet: 'cryo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'eleMas', 'atk_', 'atk'],
	},
	Eula: {
		key: 'Eula',
		role: 'DPS',
		weapon: [
			'SongOfBrokenPines',
			['WolfsGravestone', 'BeaconOfTheReedSea', 'SerpentSpine'],
			'RedhornStonethresher',
			'TheUnforged',
			'SkywardPride',
			'TidalShadow',
			['LuxuriousSeaLord', 'Akuoumaru'],
			'LithicBlade',
			'PrototypeArchaic',
			'SnowTombedStarsilver',
			'SkyriderGreatsword',
		],
		artifact: ['PaleFlame', 'GladiatorsFinale'],
		mainStat: { sands: 'atk_', goblet: 'physical_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'enerRech_', 'atk_', 'atk'],
	},
	KamisatoAyaka: {
		key: 'KamisatoAyaka',
		role: 'DPS',
		weapon: [
			'MistsplitterReforged',
			'HaranGeppakuFutsu',
			['LightOfFoliarIncision', 'PrimordialJadeCutter', 'SummitShaper'],
			'FinaleOfTheDeep',
			['AquilaFavonia', 'SkywardBlade'],
			['AmenomaKageuchi', 'TheBlackSword', 'KagotsurubeIsshin'],
			'HarbingerOfDawn',
		],
		artifact: ['BlizzardStrayer'],
		mainStat: { sands: 'atk_', goblet: 'cryo_dmg_', circlet: ['critDMG_', 'atk_'] },
		subStat: ['critDMG_', 'atk_', 'enerRech_', 'critRate_', 'atk'],
	},
	Aloy: {
		key: 'Aloy',
		role: 'Burst Support',
		weapon: [
			'ThunderingPulse',
			'PolarStar',
			'SkywardHarp',
			'TheStringless',
			'AmosBow',
			'AlleyHunter',
			'PrototypeCrescent',
			'Predator',
			'SacrificialBow',
			'Slingshot',
		],
		artifact: ['BlizzardStrayer', 'EmblemOfSeveredFate', 'NoblesseOblige'],
		mainStat: { sands: ['atk_', 'eleMas'], goblet: 'cryo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'eleMas', 'enerRech_', 'atk'],
	},
	Shenhe: {
		key: 'Shenhe',
		role: 'Support',
		weapon: [
			'CalamityQueller',
			'EngulfingLightning',
			'VortexVanquisher',
			'SkywardSpine',
			'FavoniusLance',
			'PrimordialJadeWingedSpear',
			'LithicSpear',
			'StaffOfHoma',
			'WavebreakersFin',
			'MissiveWindspear',
			'PrototypeStarglitter',
		],
		artifact: ['NoblesseOblige'],
		mainStat: { sands: ['atk_', 'enerRech_'], goblet: 'atk_', circlet: 'atk_' },
		subStat: ['enerRech_', 'atk_', 'critRD_', 'atk'],
	},
	Wriothesley: {
		key: 'Wriothesley',
		role: 'Freeze DPS',
		weapon: [
			['CashflowSupervision', 'TulaytullahsRemembrance'],
			[
				'MemoryOfDust',
				'TomeOfTheEternalFlow',
				'KagurasVerity',
				'LostPrayerToTheSacredWinds',
				'SkywardAtlas',
			],
			['BalladOfTheBoundlessBlue', 'TheWidsith'],
			'FlowingPurity',
		],
		artifact: ['MarechausseeHunter', ['BlizzardStrayer', 'ShimenawasReminiscence']],
		mainStat: { sands: 'atk_', goblet: 'cryo_dmg_', circlet: 'critDMG_' },
		subStat: ['critRD_', 'atk_', 'atk', 'enerRech_'],
	},
	// Anemo
	Sucrose: {
		key: 'Sucrose',
		role: 'EM Build',
		weapon: [
			'AThousandFloatingDreams',
			'SacrificialFragments',
			'ThrillingTalesOfDragonSlayers',
			'HakushinRing',
			'MagicGuide',
			'FavoniusCodex',
		],
		artifact: ['ViridescentVenerer', 'Instructor'],
		mainStat: { sands: 'eleMas', goblet: 'eleMas', circlet: 'eleMas' },
		subStat: ['eleMas', 'enerRech_', 'atk_', 'critRD_'],
	},
	Sayu: {
		key: 'Sayu',
		role: 'Support',
		weapon: [
			'FavoniusGreatsword',
			'WolfsGravestone',
			'KatsuragikiriNagamasa',
			'SkywardPride',
			'SacrificialGreatsword',
			'MakhairaAquamarine',
			'MailedFlower',
			'ForestRegalia',
			'Rainslasher',
			'BloodtaintedGreatsword',
		],
		artifact: ['ViridescentVenerer', 'NoblesseOblige', 'OceanHuedClam'],
		mainStat: {
			sands: ['enerRech_', 'eleMas'],
			goblet: ['eleMas', 'atk_'],
			circlet: ['heal_', 'eleMas'],
		},
		subStat: ['enerRech_', 'eleMas', 'atk_', 'critRate_'],
	},
	ShikanoinHeizou: {
		key: 'ShikanoinHeizou',
		role: 'Anemo DPS',
		weapon: [
			['KagurasVerity', 'SkywardAtlas'],
			'LostPrayerToTheSacredWinds',
			'MemoryOfDust',
			['SacrificialFragments', 'TheWidsith'],
			['MappaMare', 'SolarPearl'],
		],
		artifact: ['ViridescentVenerer', 'GoldenTroupe', 'DesertPavilionChronicle'],
		mainStat: { sands: 'atk_', goblet: 'anemo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'eleMas'],
	},
	Faruzan: {
		key: 'Faruzan',
		role: 'Support',
		weapon: [
			'FavoniusWarbow',
			'ElegyForTheEnd',
			'EndOfTheLine',
			['FadingTwilight', 'SacrificialBow'],
		],
		artifact: [
			['ViridescentVenerer', 'NoblesseOblige'],
			'EmblemOfSeveredFate',
			['GoldenTroupe', 'TenacityOfTheMillelith'],
		],
		mainStat: { sands: 'enerRech_', goblet: 'anemo_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRate_', 'critDMG_', 'atk_', 'atk'],
	},
	Lynette: {
		key: 'Lynette',
		role: 'Off-Field DPS',
		weapon: [
			'FavoniusSword',
			['FleuveCendreFerryman', 'SacrificialSword', 'AmenomaKageuchi', 'SkywardBlade'],
			'FreedomSworn',
		],
		artifact: ['ViridescentVenerer', 'EmblemOfSeveredFate', 'NoblesseOblige'],
		mainStat: { sands: ['enerRech_', 'atk_'], goblet: 'anemo_dmg_', circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRate_', 'critDMG_', 'atk_', 'atk'],
	},
	Jean: {
		key: 'Jean',
		role: 'Burst Support',
		weapon: [
			'PrimordialJadeCutter',
			'FreedomSworn',
			['MistsplitterReforged', 'HaranGeppakuFutsu'],
			['SkywardBlade', 'FesteringDesire', 'FavoniusSword', 'AmenomaKageuchi'],
			'SummitShaper',
			'AquilaFavonia',
			['TheFlute', 'SapwoodBlade', 'LionsRoar'],
		],
		artifact: ['ViridescentVenerer', 'NoblesseOblige', 'OceanHuedClam', 'EmblemOfSeveredFate'],
		mainStat: {
			sands: ['atk_', 'enerRech_', 'eleMas'],
			goblet: ['anemo_dmg_', 'eleMas'],
			circlet: ['critRD_', 'eleMas'],
		},
		subStat: ['critRD_', 'atk_', 'enerRech_', 'eleMas', 'atk'],
	},
	Venti: {
		key: 'Venti',
		role: 'Reaction Off-Field DPS',
		weapon: [
			'ElegyForTheEnd',
			'TheStringless',
			['WindblumeOde', 'PolarStar'],
			'FavoniusWarbow',
			['RavenBow', 'FadingTwilight'],
			['AlleyHunter', 'MouunsMoon'],
			'SongOfStillness',
		],
		artifact: ['ViridescentVenerer', 'NoblesseOblige', 'GildedDreams'],
		mainStat: { sands: 'eleMas', goblet: 'eleMas', circlet: 'eleMas' },
		subStat: ['eleMas', 'enerRech_', 'atk_', 'critRD_', 'atk'],
	},
	Xiao: {
		key: 'Xiao',
		role: 'DPS',
		weapon: [
			'PrimordialJadeWingedSpear',
			'StaffOfHoma',
			['VortexVanquisher', 'CalamityQueller', 'StaffOfTheScarletSands'],
			'Deathmatch',
			'LithicSpear',
			'MissiveWindspear',
			['BlackcliffPole', 'SkywardSpine', 'MissiveWindspear'],
			'EngulfingLightning',
			['FavoniusLance', 'WhiteTassel'],
		],
		artifact: ['VermillionHereafter', ['DesertPavilionChronicle', 'MarechausseeHunter']],
		mainStat: { sands: 'atk_', goblet: ['anemo_dmg_', 'atk_'], circlet: 'critRD_' },
		subStat: ['enerRech_', 'critRD_', 'atk_', ['eleMas', 'atk']],
	},
	KaedeharaKazuha: {
		key: 'KaedeharaKazuha',
		role: 'Reaction DPS & Support',
		weapon: [
			['FreedomSworn', 'XiphosMoonlight'],
			'FavoniusSword',
			[
				'IronSting',
				'ToukabouShigure',
				'SacrificialSword',
				'FleuveCendreFerryman',
				'SapwoodBlade',
				'SkywardBlade',
			],
		],
		artifact: ['ViridescentVenerer', 'Instructor', 'ThunderingFury'],
		mainStat: { sands: ['eleMas', 'enerRech_'], goblet: 'eleMas', circlet: 'eleMas' },
		subStat: ['enerRech_', 'eleMas', ['atk_', 'critRate_']],
	},
	Wanderer: {
		key: 'Wanderer',
		role: 'DPS',
		weapon: [
			'TulaytullahsRemembrance',
			'LostPrayerToTheSacredWinds',
			'TheWidsith',
			['KagurasVerity', 'TomeOfTheEternalFlow', 'SkywardAtlas', 'MemoryOfDust'],
			['SolarPearl', 'DodocoTales'],
			'BalladOfTheBoundlessBlue',
			'BlackcliffAgate',
			'EyeOfPerception',
			['MappaMare', 'Frostbearer'],
		],
		artifact: [
			'DesertPavilionChronicle',
			'ShimenawasReminiscence',
			'EchoesOfAnOffering',
			'BlizzardStrayer',
			'Lavawalker',
			'ViridescentVenerer',
		],
		mainStat: { sands: 'atk_', goblet: 'anemo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'atk', 'eleMas', 'enerRech_'],
	},
	// Geo
	Ningguang: {
		key: 'Ningguang',
		role: 'DPS',
		weapon: [
			'LostPrayerToTheSacredWinds',
			'KagurasVerity',
			'SkywardAtlas',
			'MemoryOfDust',
			'SolarPearl',
			'TheWidsith',
			'FlowingPurity',
			'EyeOfPerception',
			'DodocoTales',
			'WineAndSong',
			'MappaMare',
			'HakushinRing',
		],
		artifact: [
			['ArchaicPetra', 'HuskOfOpulentDreams'],
			['Thundersoother', 'Lavawalker'],
			'EmblemOfSeveredFate',
		],
		mainStat: { sands: 'atk_', goblet: 'geo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'atk_', 'enerRech_', 'atk'],
	},
	Noelle: {
		key: 'Noelle',
		role: 'DPS',
		weapon: [
			'RedhornStonethresher',
			'SerpentSpine',
			'SkywardPride',
			'Whiteblind',
			'FavoniusGreatsword',
		],
		artifact: [['RetracingBolide', 'HuskOfOpulentDreams'], 'GladiatorsFinale'],
		mainStat: { sands: ['def_', 'atk_'], goblet: 'geo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'enerRech_', 'def_'],
	},
	Gorou: {
		key: 'Gorou',
		role: 'Support',
		weapon: ['FavoniusWarbow', 'SacrificialBow', 'ElegyForTheEnd'],
		artifact: ['TheExile', 'NoblesseOblige'],
		mainStat: {
			sands: 'enerRech_',
			goblet: ['geo_dmg_', 'def_'],
			circlet: ['critRate_', 'def_', 'heal_'],
		},
		subStat: ['enerRech_', 'def_', 'critRate_'],
	},
	YunJin: {
		key: 'YunJin',
		role: 'Support',
		weapon: [
			'FavoniusLance',
			'EngulfingLightning',
			['TheCatch', 'PrototypeStarglitter', 'KitainCrossSpear'],
		],
		artifact: ['HuskOfOpulentDreams', 'NoblesseOblige'],
		mainStat: { sands: ['def_', 'enerRech_'], goblet: 'def_', circlet: ['def_', 'critRate_'] },
		subStat: ['def_', 'enerRech_', 'def', 'critRate_'],
	},
	Zhongli: {
		key: 'Zhongli',
		role: 'Shield Support',
		weapon: ['BlackTassel', 'FavoniusLance'],
		artifact: ['TenacityOfTheMillelith', 'ArchaicPetra', ['DeepwoodMemories', 'Instructor']],
		mainStat: { sands: 'hp_', goblet: 'hp_', circlet: ['hp_', 'critRate_'] },
		subStat: ['hp_', 'hp', 'enerRech_'],
	},
	Albedo: {
		key: 'Albedo',
		role: 'Off-Field DPS',
		weapon: [
			'CinnabarSpindle',
			['HarbingerOfDawn', 'WolfFang', 'PrimordialJadeCutter'],
			['LightOfFoliarIncision', 'HaranGeppakuFutsu', 'MistsplitterReforged'],
			'FreedomSworn',
		],
		artifact: [
			['HuskOfOpulentDreams', 'GoldenTroupe'],
			'ArchaicPetra',
			'TenacityOfTheMillelith',
			'NoblesseOblige',
		],
		mainStat: { sands: 'def_', goblet: 'geo_dmg_', circlet: ['critRD_', 'def_'] },
		subStat: ['critRD_', 'def_', 'atk_', 'enerRech_'],
	},
	AratakiItto: {
		key: 'AratakiItto',
		role: 'DPS',
		weapon: ['RedhornStonethresher', 'SerpentSpine', 'SkywardPride', 'Whiteblind'],
		artifact: ['HuskOfOpulentDreams', 'DesertPavilionChronicle', 'RetracingBolide'],
		mainStat: { sands: 'def_', goblet: 'geo_dmg_', circlet: 'critRD_' },
		subStat: ['critRD_', 'def_', 'enerRech_', 'atk_', 'def', 'atk'],
	},
};

export const elementsInfo: Record<string, DElement> = data.elements;
